### ISSUE TITLE
Option to use Native Titlebars?

### ISSUE THREAD

**Issue by feren** [oguzhaninan/Stacer#10]
This application looks awesome, but the downside is that it looks a bit to macOS-ish on the titlebars, it'd be better looking on most distributions if you had the option of Native Titlebars...

**Comment by oguzhaninan** [comment]
Thanks for the recommendation.
I think I will change in the new version

**Comment by oguzhaninan** [comment]
I released the new version.

**Comment by feren** [comment]
Ok.
