### ISSUE TITLE
System Startup Apps not matching OS Startup Apps

### ISSUE THREAD

**Issue by drohm** [oguzhaninan/Stacer#112]
I installed the latest version (1.0.8) and noticed that the enabled/disabled System Startup Apps don't match the Startup apps for the system (refer to screenshot).

![stacer-startup-apps-not-matching](https://user-images.githubusercontent.com/184959/29680419-793c5b64-88d2-11e7-9ace-9a90baac07e1.png)

System Info:
* Ubuntu Budgie 17.04
* Kernel version: 4.10.0-30-generic #34-Ubuntu

**Comment by oguzhaninan** [comment]
Would you run `ls ~/.config/autostart` and give output? Stacer uses the files in this directory.

**Comment by drohm** [comment]
Here's the output:

> -rw-r--r--  1 drohm drohm  283 Dec 26  2016 AirVPN.desktop
> -rw-r--r--  1 drohm drohm  172 May  1 23:48 Albert.desktop
> -rw-rw-r--  1 drohm drohm  172 May  2 00:33 anydesk.desktop
> -rw-rw-r--  1 drohm drohm  240 May  2 00:35 budgie-plank.desktop
> -rw-r--r--  1 drohm drohm  370 Aug 24 23:24 keybase_autostart.desktop
> -rw-r--r--  1 drohm drohm  182 May  1 23:48 nVidia GPU Fan Speed.desktop
> -rwxr-xr-x  1 drohm drohm  306 May  2 02:40 nVidia Indicator.desktop
> -rw-rw-r--  1 drohm drohm  199 Jun 25 01:46 ownCloud.desktop
> -rw-rw-r--  1 drohm drohm  177 May  2 00:32 PomoDoneApp.desktop
> -rw-rw-r--  1 drohm drohm 1868 May  3 21:34 redshift-gtk.desktop
> -rw-rw-r--  1 drohm drohm  206 May  2 02:58 remmina-applet.desktop
> -rw-rw-r--  1 drohm drohm  532 Jun 25 20:00 shutter.desktop
> -rw-r--r--  1 drohm drohm 2218 May  2 03:03 steam.desktop
> -rw-rw-r--  1 drohm drohm  188 May  1 21:31 Telegram.desktop
> -rw-rw-r--  1 drohm drohm  250 Aug 22 19:06 ukuu.desktop

**Comment by oguzhaninan** [comment]
Stacer files are listed correctly.

**Comment by drohm** [comment]
Do you think maybe Stacer should look in other areas since there can be other autostart entries elsewhere in the system?

**Comment by oguzhaninan** [comment]
It is also available in `/etc/xdg/autostart` directory. But this is for all users. Stacer only shows current user applications.
See also 
https://specifications.freedesktop.org/autostart-spec/0.5/ar01s02.html
https://askubuntu.com/questions/63407/where-are-startup-commands-stored

**Comment by drohm** [comment]
What about the issue of, for example Albert?  It's listed, but the status in Stacer is its off (it's on in system startups).  There are a few that are like this.

**Comment by oguzhaninan** [comment]
Sorry for delay. Would you run `cat ~/.config/autostart/Albert.desktop` and give output?

**Comment by drohm** [comment]
It *was* this:
```
[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=Albert
Comment=A desktop agnostic launcher
Exec=albert

StartupNotify=false
Terminal=false
Hidden=false
```
which didn't show it enabled in Stacer.  I changed it to this:
```
[Desktop Entry]
Name=Albert
Comment=A desktop agnostic launcher
Exec=albert
Version=0.9.4
Terminal=false
Type=Application
Categories=Accessories
X-GNOME-Autostart-enabled=true
NoDisplay=false
Hidden=false
Name[en_US]=Albert
Comment[en_US]=A desktop agnostic launcher
X-GNOME-Autostart-Delay=0
```
and Stacer properly shows it enabled.  What exactly is Stacer looking for in the ```.desktop``` files to reflect if the application is enabled or not?

**Comment by oguzhaninan** [comment]
If the "X-GNOME-Autostart-enabled" value is not present or false, disable. Enabled if "X-GNOME-Autostart-enabled = true".

**Comment by drohm** [comment]
Okay, I'll go through all my ```.desktop``` files and check for that attribute.

**Comment by oguzhaninan** [comment]
It's wrong because of the hidden value. In the new version I'm going to fix this. Thank you for helping me.
