### ISSUE TITLE
Appimage doesn't start

### ISSUE THREAD

**Issue by gspe** [oguzhaninan/Stacer#113]
Hi I've downloaded the Appimage version v1.0.8 but when I try to start it I get this message:
```
./Stacer-x64.AppImage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.

```

**Comment by oguzhaninan** [comment]
Hi,
I fixed the problem. You can download it from [Github](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.8). 
My fault. The file in the sourceforge is incorrect. I'll update.

**Comment by jmaris** [comment]
Still having the issue here with latest build on Archlinux

**Comment by oguzhaninan** [comment]
I tested Arch linux there is no problem. 
Where did you download the file.

**Comment by ghost** [comment]
Downloaded from GitHub link and source forge. it doesn't work on Arch Linux. those two files are same. verified by checksum.

**Comment by oguzhaninan** [comment]
Would you like to run "uname -a". What you got is the mistake.

**Comment by gspe** [comment]
Hi I've re-downloaded from github and I have the same error

my uname -a is:
```
uname -a
Linux jura 4.12.8-2-MANJARO #1 SMP PREEMPT Sun Aug 20 08:24:42 UTC 2017 x86_64 GNU/Linux
```

**Comment by oguzhaninan** [comment]
This problem is only in arch linux. Fedora and debian are also running AppImage. I am trying to solve the problem as soon as possible.

**Comment by gspe** [comment]
The last version on github/release open K3b!

**Comment by probonopd** [comment]
The problem persists in the latest release:
https://travis-ci.org/AppImage/appimage.github.io/builds/268441260#L592-L595

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
Available platform plugins are: xcb.
```

How do you produce the AppImage? Normally `linuxdeployqt` should take care of these things for you.

**Comment by probonopd** [comment]
> The last version on github/release open K3b!

Please make it executable first.

**Comment by oguzhaninan** [comment]
I use [deploy.sh](https://github.com/oguzhaninan/Stacer/blob/native/deploy.sh) script to generate AppImage. Fedora and debian are also running AppImage.
`./deploy.sh appimage`

**Comment by probonopd** [comment]
The issue can be reproduced. Would it be OK for you to build Stacer on Travis CI using https://launchpad.net/~beineri/+archive/ubuntu/opt-qt59-trusty? I am pretty sure it would work then. There are many examples on how to do this at https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci

**Comment by probonopd** [comment]
I have started working on it at https://github.com/probonopd/Stacer/blob/patch-1/.travis.yml but am currently blocked by https://github.com/oguzhaninan/Stacer/issues/123.

**Comment by oguzhaninan** [comment]
I could not install "opt-qt59-trusty".
I run
- `sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y`
- `sudo apt-get update -qq`
- `sudo apt-get -y install qt59base`

**Comment by oguzhaninan** [comment]
I do not know what to do.

**Comment by oguzhaninan** [comment]
I do not know what to do.

**Comment by oguzhaninan** [comment]
I installed qt59base qt59svg qt59charts-no-lgpl. 
But the problem is still going on. Arch linux is not working either.

**Comment by probonopd** [comment]
I can _successfully_ compile on Travis CI, but installation fails since `make install` does not respect `INSTALL_ROOT` - can you fix this?

**Comment by oguzhaninan** [comment]
I do not know how to do it. :confused:

**Comment by probonopd** [comment]
Apparently there is a shell script `install.sh` involved. Possibly you could get rid of it and let the qmake system do this stuff natively, by editing the `.pro` file.

https://doc-snapshots.qt.io/qt5-dev/qmake-variable-reference.html#destdir

**Comment by oguzhaninan** [comment]
@gspe @jmaris @arunsai123 I solved the problem and tested it. You can download the AppImage package to try it out.

**Comment by gspe** [comment]
Tested and it's working now.
Thanks.
