### ISSUE TITLE
The CPU History plot just plots either 100% or 0% values in KDE Neon (Ubuntu 16.04)

### ISSUE THREAD

**Issue by kleiren** [oguzhaninan/Stacer#115]
I am using KDE neon User edition 5.10. Its based on Ubuntu 16.04.
On my system, the CPU history viewer just shows either 100% or 0% values, unlike the system monitor that shows real values. You can see the difference in the image. I guess this is a bug.

![image](https://user-images.githubusercontent.com/5618792/29706745-32802e06-8983-11e7-9d63-0c1842baff26.png)

Good job by the way, very nice app.

**Comment by oguzhaninan** [comment]
Thank you for reporting. Sometimes that happens. 
When you turn it off, you need to fix it. I will fixed.
