### ISSUE TITLE
Almost certainly horribly insecure, please rip out and replace the sudo and command substitution code

### ISSUE THREAD

**Issue by nickalcock** [oguzhaninan/Stacer#12]
So I was attracted to this by a G+ posting, and, uh, at first sight it looks really pretty, but... is that a hardwired list of commands? Being shoved through sudo in sudoCommand()? With a password with no quoting, echoed with 'echo' so if it contains any shell metacharacters it'll execute arbitrary code as the user? (It is also exposed to the wildly varying set of switches echo implements, so depending on the phase of the moon and the echo implementation passwords starting with - might cause misbehaviour. The right way to print arbitrary stuff from the shell is "printf "%s" '...', but even then you have to escape single-quote characters and backslashes in the input string.)

The command list is hardcoded, but even that is unsafe because many of the commands have parameters derived from the client and substituted in without any quoting of any kind: app-cache-check, apt-cache-check, log-check and crash-check (which has another obvious bug in the initialization of "crashLen") at least are vulnerable, and probably more.

Please at least take the sudo stuff out or wrap a great big fat warning around all of this. This is *not safe*. Maybe the framework is protecting you against XSS attacks (I dunno, I'm a system programmer, not a web guy), but holy crap this code is making me break out in a cold sweat just reading it. You should be doing this sort of thing by calling into a dbus service or adding sudo snippets with fixed commands and parameter lists (and with defaults reset for those commands to safe values) to a file in /etc/sudoers.d and then using a pipe to pass any variable data into each sudoed program before execution, sanitizing it on both sides with great care. (Yes, this means you need to write the sudoed programs too -- carefully!)

But honestly something like PackageKit or whatever analogue Ubuntu uses would seem a better fit for most of what these sudo commands are doing -- and that has someone else dealing with all the security problems.

**Comment by fergalmoran** [comment]
Agreed - I installed this (probably based on the same G+ post), saw the electron dialog asking me for my password for sudo purposes, bailed out and uninstalled it. This is crazy dangerous code.

**Comment by nickalcock** [comment]
To be fair, use of sudo and asking for your password is not *necessarily* a sign of insecure code (though typing it into a web app is... iffy if you don't have a one-time password system set up). But in this case... well, oh dear.

**Comment by fergalmoran** [comment]
@nickalcock It should hook into gksudo instead of asking for the password in a plain text box, there's even an electron lib already for this purpose.
https://github.com/automation-stack/electron-sudo

**Comment by oguzhaninan** [comment]
I released the new version

**Comment by nickalcock** [comment]
OK, that's definitely better -- but it's still using entirely unquoted filenames in calls to rm -r, which means that one file called, say, "; rm -rf *" could ruin your whole day. You really shouldn't be using rm(1) via a shell to remove files at all...
