### ISSUE TITLE
Rearranging the file and folder structure

### ISSUE THREAD

**Issue by lilianmoraru** [oguzhaninan/Stacer#121]
@oguzhaninan I would like to rearrange the file and folder structure to make it more consistent and ease project file maintenance.
The idea is to have all:
- `.cpp` under `src`
- `.h` under `include`
- `.ui` under `ui`

I also replaced all the `-` with `_` because it makes it easier to work with tools(especially when using regexes)

What do you think of such a structure?:
```
stacer
├── stacer
│  ├── include
│  │  ├── app.h
│  │  ├── managers
│  │  └── pages
│  │     ├── dashboard
│  │     ├── processes
│  │     ├── resources
│  │     ├── services
│  │     ├── settings
│  │     ├── startup_apps
│  │     ├── system_cleaner
│  │     └── uninstaller
│  ├── src
│  │  ├── app.cpp
│  │  ├── main.cpp
│  │  ├── managers
│  │  └── pages
│  │     ├── dashboard
│  │     ├── processes
│  │     ├── resources
│  │     ├── services
│  │     ├── settings
│  │     ├── startup_apps
│  │     ├── system_cleaner
│  │     └── uninstaller
│  └── ui
│     ├── app.ui
│     ├── managers
│     └── pages
│        ├── dashboard
│        ├── processes
│        ├── resources
│        ├── services
│        ├── settings
│        ├── startup_apps
│        ├── system_cleaner
│        └── uninstaller
└── stacer_core
   ├── include
   │  ├── info
   │  ├── stacer_core_global.h
   │  ├── tools
   │  └── utils
   └── src
      ├── info
      ├── tools
      └── utils
```

**Comment by lilianmoraru** [comment]
To explain `ease project file maintenance`, for example: you can recurse all the `.cpp` files in the `src` directory and not worry that new files won't be captured.
But of course, the developer now has to take a little bit more care to put the files in their correct place.

**Comment by oguzhaninan** [comment]
@lilianmoraru  Thank you very much for your suggestion. But with the current state, the files are more accessible. For example app.cpp, app.h and app.ui are side-by-side. Actually, your suggestion is more organized. But the files may be good even if they are not separated.
