### ISSUE TITLE
Why Electron exists!

### ISSUE THREAD

**Issue by mbnoimi** [oguzhaninan/Stacer#125]
Hi,

I wonder why Electron branch exists?!

Qt Widgets works fine without need to use Electron. Even there is Qt Quick works better than Electron!

**Comment by mbnoimi** [comment]
http://sircmpwn.github.io/2016/11/24/Electron-considered-harmful.html

**Comment by lilianmoraru** [comment]
@mbnoimi Probably developer's preference and maybe some users prefer it.
I don't see harm in that branch existing.

**Comment by oguzhaninan** [comment]
@mbnoimi @lilianmoraru is right. But thanks for the warning.
