### ISSUE TITLE
Unable to start stacer

### ISSUE THREAD

**Issue by ashishdoneriya** [oguzhaninan/Stacer#139]
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted

**Comment by oguzhaninan** [comment]
Which distribution you are using.

**Comment by ashishdoneriya** [comment]
Ubuntu 14.04

**Comment by oguzhaninan** [comment]
You can install the Debian package.

**Comment by ashishdoneriya** [comment]
I installed the debian package.

**Comment by oguzhaninan** [comment]
Any problems? 
There are some issues with the AppImage package. I will solve it shortly.

**Comment by ashishdoneriya** [comment]
This bug is raised because stacer (which I installed from .deb package) is not starting. 
In Detail : 
1. I read reviews about stacer.
2. I downloaded .deb file from github, installed it, raised bug.
3. Now I was asked to install deb package again.

**Comment by oguzhaninan** [comment]
Run `sudo apt-get -f install`

**Comment by ashishdoneriya** [comment]
No effect

**Comment by ashishdoneriya** [comment]
The same error is also occuring on appimage file.
A bug has been already raised. #113

**Comment by oguzhaninan** [comment]
I tried it but it does not work in 14.04 and older versions. I will fix the error as soon as possible. You can follow the situation from [here](https://github.com/oguzhaninan/Stacer/issues/113).
