### ISSUE TITLE
stacer 1.0.8 is not integrated to the system 

### ISSUE THREAD

**Issue by Lvaskz** [oguzhaninan/Stacer#142]
Hello, in the past appimage stacer 1.0.7, at the time of making the application executable, a window would pop up and ask if you wanted to integrate the stacer appimage into the system, but in stacer appimage version 1.0.8 no longer does the question and does not integrate it into the system.

**Comment by oguzhaninan** [comment]
@probonopd do you know why?

**Comment by probonopd** [comment]
Possibly the old AppImage (where did you get it from?) used a bash script to do this.

Please use the optional `appimaged` daemon which will do this for you automatically.

**Comment by Lvaskz** [comment]
ok, how can i doit?

**Comment by probonopd** [comment]
The optional `appimaged` daemon can be installed from https://github.com/AppImage/AppImageKit/releases or possibly from your distribution.

**Comment by Lvaskz** [comment]
hi, i have already installed, but nothing happens. How it works ?

2017-09-09 22:43 GMT-06:00 probonopd <notifications@github.com>:

**Comment by probonopd** [comment]
Simply download an AppImage, it should appear automatically in the menu. Please refer to https://github.com/AppImage/AppImageKit/blob/appimagetool/master/README.md#appimaged-usage for more information.

**Comment by Lvaskz** [comment]
well, the appimaged is not working for me, but i discovered that i can add an icon from main menu settings cinnamon. So thank you

**Comment by probonopd** [comment]
Please file a bug on appimaged in the AppImageKit project so that we can fix it, thanks.
