### ISSUE TITLE
Suggestion: network limiter

### ISSUE THREAD

**Issue by t0msk** [oguzhaninan/Stacer#143]
Hello,

what about adding a new feature, something like network limiter per application, here is screenshot:

https://www.netlimiter.com/files/imagegalleries/docs/client-full-new.png

Thank you

**Comment by twardakm** [comment]
Hello!

Personally, I love the idea! Maybe we could use trickle (https://github.com/mariusae/trickle)?

If you like the idea of trickle (or have a better one) I would love to contribute and add the functionality.

Marcin

**Comment by t0msk** [comment]
Yea, it would be great to implement Trickle core into Stacer, to have a GUI option too :)

**Comment by twardakm** [comment]
I was thinking about adding Trickle as a dependency - it's available in most distributions' repositories :) Maybe we shouldn't make it a required dependency, only a suggested one and the feature would be available only if it's installed.

I will definitely take a deeper look into the idea during the weekend :)

**Comment by t0msk** [comment]
So do you mean that Stacker calls Trickle? Yea it is possible too, @oguzhaninan what is your opinion?

**Comment by twardakm** [comment]
Yes, exactly this is how I would implement the network limiter functionality.

**Comment by oguzhaninan** [comment]
@t0msk idea is really great. Thanks for recommending @twardakm. It would be great if you could. If you can not, I think about adding it for the new version. Thanks again for the suggestion, @t0msk .

**Comment by twardakm** [comment]
That's great you like the idea! I will work on this issue :)

**Comment by t0msk** [comment]
Great :) Maybe then I could create a standalone app (GUI frontend for Trickle) for network limiter (to be lightweight as much as possible).

Anyway I started creating a hardware monitor app few days ago, it is going to be something like http://openhardwaremonitor.org/ but for Linux systems, I will create a repository in few days if someone is interested.

**Comment by twardakm** [comment]
@t0msk I love openhardwaremonitor, so if you are going to do something like that for Linux, please let me know! :) I just start working on network limiter, hopefully, the first results will be on the weekend.

**Comment by t0msk** [comment]
@twardakm That's great, yes I am going to make something like that but only for Linux systems (Windows doesn't need, it has lot of alternatives), because openhardwaremonitor doesn't work on Linux well.

Did you fork the project? Or do you have a own repository?

**Comment by twardakm** [comment]
@t0msk Yeah, I forked the project a few days ago
