### ISSUE TITLE
Some issues on 1.0.8.2

### ISSUE THREAD

**Issue by michaldybczak** [oguzhaninan/Stacer#145]
I installed Stacer from AUR 1.0.8.2 version. Awesome it's no longer on electron and memory usage is low. System: Manjaro, Kernel 4.12, Plasma.

However, I discovered some bugs:

1) Dashboard is not responsive: system info is not fully shown, I need to scroll down.
I wanted to resize window to make all info visible but it doesn't work. Graphics and all GUI interface was just distorted in proportions but the same amount of UI was presented after resize.

2) System Startup Apps - just doesn't work correctly
System shows turned on startups as inactive... Activating them does nothing, with next Stacer start, they're just show inactive again. In system settings startups are always shown active. When I modified some startup app, it added copy of the one I already had. So I removed the old one and left the new one and this is showed turned on correctly. This is just a mess.

3) System Services
It's not a bug per se, just it would be nice to have tooltips on cursor hover, so we would know what those columns really are. Now I just must assume that first one is startup, second is active.

4) Processes - doesn't work at all, list is empty, nothing is searched.

A nice piece of software and that is why I wanted to give some feedback.

**Comment by oguzhaninan** [comment]
Thank you very much for your feedback.

Bugs:

1. It would be great if you could send me a screenshot.

2. You can look [here](https://github.com/oguzhaninan/stacer/issues/112). 

3. It have a tooltip. 
![1](https://user-images.githubusercontent.com/16149251/30161319-b777cd08-93d8-11e7-9935-2bf9dcd13860.png)
![2](https://user-images.githubusercontent.com/16149251/30161320-b77fdc46-93d8-11e7-9b76-7b0af744c7d4.png)

4. There is a problem because the user name is long. It's not about you. I will fix a minor error in the new version. If you select "All Processes" you can see all.

Please let me know if you have a problem.
Thanks !

**Comment by michaldybczak** [comment]
1.
![screenshot_20170907_210203](https://user-images.githubusercontent.com/10132958/30180356-ea695542-940f-11e7-90b1-23e2ff766f8d.png)

![screenshot_20170907_210327](https://user-images.githubusercontent.com/10132958/30180388-03e941b2-9410-11e7-85f2-8455e9234628.png)

You can see that system info is not fully visible and needs scrolling. On window resizing, content just gets disfigured to the changed shape of a window. It looks bad and serves nothing. It's not a vital thing but it would be nice to improve it.

2. Ah, ok, then the issue is clear and will be fixed.

3. OMG, I have tooltips too. I don't know why I didn't see them before. Maybe because I had to place the cursor more carefully and wait longer to see them, but yeah, tooltips exist and work, so no issue here.

4. Ah, I marked "All processes" and then I was able to see them. That was confusing, because I didn't know it had to be marked, I thought it already is since the "All processes" above. That should have been marked as default. I even don't understand what is it for, because when unmarked, the whole tab becomes useless (nothing shows up, nothing can be searched), so it has to be on all the time. Not sure what it has to do with long usernames.

Anyway, your application should be a great tool for xfce desktops, because default system manager is so poor. Stand alone WMs should be also a nice place to use it.

**Comment by oguzhaninan** [comment]
Thank you for feedback.
