### ISSUE TITLE
Does not recognize cpu id or brand, work fine.

### ISSUE THREAD

**Issue by JmcbDino** [oguzhaninan/Stacer#148]
Only, it does not recognize the CPU id or the brand, but all other functions excellent.

![screenshot_20170908_085334](https://user-images.githubusercontent.com/10819999/30210686-e0efb39e-9473-11e7-804f-23f5674278c3.png)

**Comment by oguzhaninan** [comment]
Hi,
Would you give the command output?
Run `cat /proc/cpuinfo | head -n 20`

**Comment by JmcbDino** [comment]
$ cat /proc/cpuinfo | head -n 20
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 16
model name      : AMD A8-4500M APU with Radeon(tm) HD Graphics
stepping        : 1
microcode       : 0x6001119
cpu MHz         : 1400.000
cache size      : 2048 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 16
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold

**Comment by oguzhaninan** [comment]
Thanks for helping me fix it in the new version.

**Comment by JmcbDino** [comment]
Thanks you for share this great software
