### ISSUE TITLE
RAM info not accurate

### ISSUE THREAD

**Issue by DrMajkrosoft** [oguzhaninan/Stacer#15]
System monitor shows different diagram.

![screenshot from 2017-02-01 16-53-30](https://cloud.githubusercontent.com/assets/12301022/22514286/1c44f598-e89f-11e6-97c6-ebef994fe6eb.png)

**Comment by oguzhaninan** [comment]
I will post a new version in a few hours. I will fix a few more problems with this problem

**Comment by oguzhaninan** [comment]
I released the new version.

**Comment by thekuom** [comment]
I'm having the same issue on 1.0.2
![stacer_screenshot](https://cloud.githubusercontent.com/assets/15683724/22574779/c558a2ec-e976-11e6-9bed-4640130c6259.png)

**Comment by oguzhaninan** [comment]
I fixed it.
