### ISSUE TITLE
Nor CPU model or speed is available

### ISSUE THREAD

**Issue by AlienKnuckle** [oguzhaninan/Stacer#150]
bash-4.4$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
Model name:          AMD Athlon(tm) X4 880K Quad Core Processor
CPU MHz:             1700.000
CPU max MHz:         4300.0000
CPU min MHz:         1700.0000
NUMA node0 CPU(s):   0-3

![screenshot from 2017-09-12 19-51-35](https://user-images.githubusercontent.com/31382035/30334640-be24ee42-97cf-11e7-9442-07daa452aa22.png)

**Comment by oguzhaninan** [comment]
Hi,
I will fix it in the new version. https://github.com/oguzhaninan/Stacer/issues/148

**Comment by AlienKnuckle** [comment]
Thank you so much.

**Comment by DroWnThePoor** [comment]
This also happens for me, I'm using similar APU also.
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 101
model name	: AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C+8G

**Comment by oguzhaninan** [comment]
Thanks ! @DroWnThePoor
