### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by sikenali** [oguzhaninan/Stacer#152]
![deepinscreenshot_select-area_20170918131445](https://user-images.githubusercontent.com/26103116/30529772-a072cb1e-9c73-11e7-8c3a-17cf31459eb2.png)

http://appstore.deepin.org/

**Comment by oguzhaninan** [comment]
Hi,
There is Chinese support. Available in new version. https://github.com/oguzhaninan/Stacer/blob/native/translations/stacer_zh-cn.ts

**Comment by sikenali** [comment]
OK
