### ISSUE TITLE
"Resources" GUI Improvement

### ISSUE THREAD

**Issue by Snuggle** [oguzhaninan/Stacer#155]
Hey, there!

Could we please get something closer to how the old resources looked? In my opinion, the old resources page looked cleaner and I love to use this program to display system usage information on my monitor.

Here are a couple of things which I feel are improvements:
- Smoothed CPU usage, memory usage, network usage graph. Not just hard, straight lines.
- The expand buttons on the right, so that the "CPU History" headers can be left-aligned.
- I feel like the key/colours for the graphs look a bit cleaner in the old version. They're simple and easy to understand. Maybe make it so that you can hover/click on the headers for extra information.
- Grey/dark graph lines and numbers instead of pure white; doesn't pop out too much and reduces visual clutter.

(Left is the old version, while the right side is the C++ rewrite.)
![image](https://user-images.githubusercontent.com/26250962/31510755-535da700-af7d-11e7-9cb6-7edb2519b7eb.png)

**Comment by oguzhaninan** [comment]
Hi,
Thank you very much for your feedback. I will fix it in the new version.
