### ISSUE TITLE
Mistranslated word from English to Spanish

### ISSUE THREAD

**Issue by angelomarquez177** [oguzhaninan/Stacer#162]
On the "System Cleaner" screen, the word "Espalda" appears, when the correct translation is "**Volver**". I guess this mistake is repeated on the rest of the screens.
![stacer_](https://user-images.githubusercontent.com/33205030/32147704-e3be6518-bcc1-11e7-8d8d-99b958b26e1a.jpg)

**Comment by oguzhaninan** [comment]
Hi,
I fixed the typo. Thanks !
