### ISSUE TITLE
Couldn't install correctly for Linux Mint 17.3 

### ISSUE THREAD

**Issue by ocobacho** [oguzhaninan/Stacer#164]
showing this error: stacer error This application failed to start because it could not find or load the Qt platform plugin "xcb"

downloaded from https://github.com/oguzhaninan/Stacer/releases/download/v1.0.8/stacer_1.0.8_amd64.deb

**Comment by oguzhaninan** [comment]
Hi,
Sorry for delay. Have you tried the [AppImage](https://github.com/oguzhaninan/Stacer/releases/download/v1.0.8/Stacer-x64.AppImage) package ?

**Comment by nedkellddv** [comment]
Get the same error message, the AppImage package works, but would like to install the app
This is the error message:

> This application failed to start because it could not find or load the Qt platform plugin "xcb"
> in "".
> 
> Available platform plugins are: xcb.
> 
> Reinstalling the application may fix this problem.
> Aborted

**Comment by oguzhaninan** [comment]
Hi,
I have updated and tested Debian and AppImage packages.
![screenshot from 2018-02-13 09-17-42](https://user-images.githubusercontent.com/16149251/36135967-24cdbb0e-109f-11e8-8822-89186a281197.png)
