### ISSUE TITLE
Provide a 32 bit binary

### ISSUE THREAD

**Issue by khurshid-alam** [oguzhaninan/Stacer#165]
It would be nice if we could have 32 bit binary in releases. Thanks.

**Comment by tigefa4u** [comment]
i need 32bit version :+1:

**Comment by kellie-williams** [comment]
Hi, I am using the 32 bit version and it is telling me there are updates but when I click it takes me to the latest version which is 64 bit I believe as it doesn't install.
I cannot seem to do a scan, I click scan and nothing happens.
![2018-03-02-233444_1280x800_scrot](https://user-images.githubusercontent.com/37004487/36926960-6eec4576-1e72-11e8-8b2f-fb7302a0a403.png)
![2018-03-02-231429_1280x800_scrot](https://user-images.githubusercontent.com/37004487/36926989-994ae566-1e72-11e8-8090-f81418ffbc06.png)
I'm not very good with all this and I am new to Linux so go easy on me. :)

**Comment by oguzhaninan** [comment]
Hi, @kellie-williams 
You're using an old version. The last version does not have 32 bits. But soon I will release a new version (1.0.9) with 32bit support.

**Comment by liberodark** [comment]
Hi,

Seriously x32 is too old support x64 is better to concentrate on one arch !

Cordialy

**Comment by khurshid-alam** [comment]
You don't need to support both. On debian yo can use MultiArch during compilation or simply use `arch: all` which I think the ppa does. It gives [stacer-*-all.deb](https://launchpad.net/~oguzhaninan/+archive/ubuntu/stacer/+packages). But it does it in a wrong way. When I run on 32 bit I get,

`bash: /usr/bin/stacer: cannot execute binary file: Exec format error`

At least fix the ppa build.

Edit: Ppa build can't be fixed because it doesn't compile the binary. Instead it just copies the binary to /usr/bin. Just compile it with `arch:all` on your local machine and use that binary instead.

**Comment by oguzhaninan** [comment]
I decided not to publish 32 bit binary for Stacer. Only 64 bit binary.
