### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by devildefu** [oguzhaninan/Stacer#166]
I tried to compile Stacer for Manjaro i686, but when compiling it displays an error, logs:

https://hastebin.com/axigadusez.pas

Stacer version: 1.0.8 (newest)
I am counting on the solution of the error

**Comment by oguzhaninan** [comment]
Hi,
Would you try using clang. Try the steps [here](https://github.com/oguzhaninan/Stacer/blob/native/.travis.yml#L5-L17).

**Comment by devildefu** [comment]
Stacer compiles correctly by changing the compiler on the clang.
Thank you.
