### ISSUE TITLE
what are the two buttons in service section of the app ?

### ISSUE THREAD

**Issue by daksh-sagar** [oguzhaninan/Stacer#171]
I disabled both buttons for mysql and apache2 in services section and the Stacer app itself is not able to turn on the service again, can you please provide details.

**Comment by oguzhaninan** [comment]
Hi,
Sorry for delay. The task of the buttons;
![boot](https://user-images.githubusercontent.com/16149251/35588148-cf9ce184-0610-11e8-9f0a-f5af188b9242.png) ![run](https://user-images.githubusercontent.com/16149251/35588149-cfc8be94-0610-11e8-9330-91ae363762b6.png)
__"Startup at boot?"__ Running command => `systemctl [enable | disabled] mysql.service`
__"Running Now?"__  Running command => `systemctl [start | stop] mysql.service`

You can try and run it via the command line.
