### ISSUE TITLE
Mr.oguzhan i need translate your Application "stacer Linux' From English to (Kurdish-کوردی)

### ISSUE THREAD

**Issue by KarZan-iT** [oguzhaninan/Stacer#172]
My Name (KarZan iT) in Kurdistan, of Iraq
in "Stacer" Have Some Languages But Not Have Kurdish (Kurdish-کوردی),
I added Kurdish Languages Because Some People in The World Using "Stacer"
Now I, Want in Your Program Adding (Kurdish-کوردی) Languages For "Stacer"
Can You Using Kurdish Languages in Your Program?
And Iam, Helping You By Using Some Words Who Your Added For it Iam Translating for (Kurdish-کوردی)
Thanks ...

**Comment by meesudzu** [comment]
Me too.
May i translate Stacer to Vietnamese, please?

**Comment by oguzhaninan** [comment]
Hi,
Thank you for interest. You can help by using this [file](https://raw.githubusercontent.com/oguzhaninan/Stacer/native/translations/stacer_tr.ts). You must edit the 'translation' section.
