### ISSUE TITLE
Dashboard Metrics customization

### ISSUE THREAD

**Issue by Demetrio92** [oguzhaninan/Stacer#175]
There is already a #45 requesting I/O visualization and #105 requesting GPU Load. 
I was wondering, whether we could have a way to pick what metrics to put on the dashboard. For now they are hard-coded, but maybe you could make a drop-down in the config part with available metrics (you already have functions for them) and pass the choice to the circlebar? 

It's such a beautiful front-end, and such a pity some one-liners to the terminal like I/O, Swap load etc cannot be visualized without pulling the repo and replacing the defaults in the code.

**Comment by oguzhaninan** [comment]
Hi @Demetrio92,
I think about adding it for the new version. Thanks for suggestion.
