### ISSUE TITLE
Description with Processes and Services

### ISSUE THREAD

**Issue by ankurloriya** [oguzhaninan/Stacer#178]
Provide information about processes and services which are known services/processes.
Linux/ubuntu beginner can easily understand what meaning of services/processes and what user am doing.

**Comment by Demetrio92** [comment]
the services must have good descriptions somewhere on the arch-wiki. I don't think getting them from the `man` pages would be a great idea, for instance. 
However, a dynamic parser would be rather tricky. @ankurloriya any ideas, how to implement that, without **manually** writing (even if with a lot of google/copy-paste) and maintaining descriptions for **all** possible services a potential user might have?

**Comment by oguzhaninan** [comment]
Hi,
I added the new version. I will release soon.
