### ISSUE TITLE
Stacer System Cleaner; Problem selecting categories and files to clean

### ISSUE THREAD

**Issue by BertN45** [oguzhaninan/Stacer#181]
If I click in the second screen of the system cleaner on the selection buttons, nothing happens. If I imagine a rectangle around the button and click on the lower left corner of that imaginary rectangle the item (category or file) is selected for cleaning. Note that I have to click outside the button! 
I use Ubuntu Mate 17.10 in Virtualbox 5.6.2 and just installed Stacer_x64_v1.0.8.deb

**Comment by oguzhaninan** [comment]
Hi,
You could show me with the picture?

**Comment by BertN45** [comment]
See video.
[Stacer.zip](https://github.com/oguzhaninan/Stacer/files/1721004/Stacer.zip)

**Comment by oguzhaninan** [comment]
Thank you for your feedback. 
I am aware of this situation. But It's not that difficult to pick, because it is selected when the text is clicked. But I hope I will fix it the next version.
