### ISSUE TITLE
Waiting for new release.

### ISSUE THREAD

**Issue by ankurloriya** [oguzhaninan/Stacer#182]
Last release a few months ago. We expect a new release with new features/improvements.

**Comment by oguzhaninan** [comment]
Hi, @ankurloriya 
I will release the new version in one week. I've added the features you wanted before. (https://github.com/oguzhaninan/Stacer/issues/176 https://github.com/oguzhaninan/Stacer/issues/178 https://github.com/oguzhaninan/Stacer/issues/177)

**Comment by ankurloriya** [comment]
@oguzhaninan Thank you for quick replay.
