### ISSUE TITLE
Add option to disable splash screen

### ISSUE THREAD

**Issue by simoniz0r** [oguzhaninan/Stacer#183]
I really would rather not see the splash screen, thanks.

**Comment by oguzhaninan** [comment]
Hi,
I do not intend to make such an option. The splash screen appears for a very short time.

**Comment by amiga-500** [comment]
I added the "fix" plus fixed the "--hide" option so one can launch directly to the system tray with no splash of any kind: https://github.com/oguzhaninan/Stacer/pull/490
