### ISSUE TITLE
High CPU use

### ISSUE THREAD

**Issue by simoniz0r** [oguzhaninan/Stacer#184]
I'm running the AppImage for Stacer v1.0.9, and the CPU use for stacer itself is much higher than previously (ps is also using much more CPU than before).

![image](https://user-images.githubusercontent.com/16279904/37244893-706c9ca0-2455-11e8-9b59-e1f342505698.png)

**Comment by oguzhaninan** [comment]
Hi, @simoniz0r 
In the next version I will try to reduce CPU usage. Thanks !

**Comment by simoniz0r** [comment]
Thanks!
