### ISSUE TITLE
Add option to disable using system tray

### ISSUE THREAD

**Issue by simoniz0r** [oguzhaninan/Stacer#185]
It's really not even obvious that Stacer will be closed to the system tray as it does not warn or ask, and I personally do not want it to ever be in my system tray.  I'd rather just load it up when I want to use it.  Thanks.

**Comment by oguzhaninan** [comment]
Hi,
I've fixed the problem and you can download and use it.

**Comment by simoniz0r** [comment]
Thank you for adding that so quickly!
