### ISSUE TITLE
Stacer v1.0.9 not work linux mint 18.3

### ISSUE THREAD

**Issue by anim4k** [oguzhaninan/Stacer#186]
thank you developer mr.Oguzhan for great software
i have probleme when i run Stacer new version in linux mint 18.3
Show me this error!!
https://i.imgur.com/UjXE65K.png
https://i.imgur.com/LZWsvnP.png
i hope to fix it thx <3

**Comment by oguzhaninan** [comment]
Hi, @anim4k 
I've fixed the problem and you can download and use it.

**Comment by rfprof** [comment]
Oğuzhan bey merhaba
Raspberry pi3 B+ modelinde Debian 9(Stretch) kullanıyorum
Stacer V1.0.9 ve 1.1.0 kurdum. Kurulum tamamlanıyor
Ancak çalışmıyor. 
Sorun nedir? Yardımcı olabilimisiniz?
Teşekkürler
Ali AKIN
rfprof@gmail.com
