### ISSUE TITLE
fedora 27 install stacer failed

### ISSUE THREAD

**Issue by dopenw** [oguzhaninan/Stacer#187]
hello,i like the stacer

but i install stacer falied.

please help me ,how can solve the issue

[root@breap Documents]# yum localinstall stacer_1.0.9_x64.rpm 
Last metadata expiration check: 0:03:46 ago on Fri 16 Mar 2018 04:55:18 PM CST.
Dependencies resolved.
======================================================================================================================================================
 Package                              Arch                           Version                               Repository                            Size
======================================================================================================================================================
Installing:
 stacer                               x86_64                         1.0.9-2                               @commandline                          29 M
Installing dependencies:
 qt5-qtcharts                         x86_64                         5.9.4-1.fc27                          updates                              575 k

Transaction Summary
======================================================================================================================================================
Install  2 Packages

Total size: 30 M
Installed size: 77 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] qt5-qtcharts-5.9.4-1.fc27.x86_64.rpm: Already downloaded                                                                                   
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr from install of stacer-1.0.9-2.x86_64 conflicts with file from package jdk1.8.0_144-2000:1.8.0_144-fcs.x86_64
  file /usr/share/icons/hicolor from install of stacer-1.0.9-2.x86_64 conflicts with file from package teamviewer-12.0.76279-0.i686
  file / from install of stacer-1.0.9-2.x86_64 conflicts with file from package filesystem-3.3-3.fc27.x86_64
  file /usr from install of stacer-1.0.9-2.x86_64 conflicts with file from package filesystem-3.3-3.fc27.x86_64
  file /usr/share from install of stacer-1.0.9-2.x86_64 conflicts with file from package filesystem-3.3-3.fc27.x86_64
  file /usr/share/applications from install of stacer-1.0.9-2.x86_64 conflicts with file from package filesystem-3.3-3.fc27.x86_64
  file /usr/share/icons from install of stacer-1.0.9-2.x86_64 conflicts with file from package filesystem-3.3-3.fc27.x86_64
  file /usr/share/icons/hicolor/128x128 from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/128x128/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/16x16 from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/16x16/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/256x256 from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/256x256/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/32x32 from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/32x32/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/64x64 from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/64x64/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor from install of stacer-1.0.9-2.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor/16x16 from install of stacer-1.0.9-2.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor/16x16/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor/256x256 from install of stacer-1.0.9-2.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor/256x256/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor/32x32 from install of stacer-1.0.9-2.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor/32x32/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/128x128 from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/128x128/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/16x16 from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/16x16/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/256x256 from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/256x256/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/32x32 from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/32x32/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/64x64 from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file /usr/share/icons/hicolor/64x64/apps from install of stacer-1.0.9-2.x86_64 conflicts with file from package atom-1.23.3-0.1.x86_64
  file / from install of stacer-1.0.9-2.x86_64 conflicts with file from package boostnote-0.10.0-2.x86_64
  file /usr from install of stacer-1.0.9-2.x86_64 conflicts with file from package boostnote-0.10.0-2.x86_64
  file /usr/share from install of stacer-1.0.9-2.x86_64 conflicts with file from package boostnote-0.10.0-2.x86_64
  file /usr/share/applications from install of stacer-1.0.9-2.x86_64 conflicts with file from package boostnote-0.10.0-2.x86_64
  file / from install of stacer-1.0.9-2.x86_64 conflicts with file from package netease-cloud-music-1.1.0-2.x86_64
  file /usr from install of stacer-1.0.9-2.x86_64 conflicts with file from package netease-cloud-music-1.1.0-2.x86_64
  file /usr/share from install of stacer-1.0.9-2.x86_64 conflicts with file from package netease-cloud-music-1.1.0-2.x86_64
  file /usr/share/applications from install of stacer-1.0.9-2.x86_64 conflicts with file from package netease-cloud-music-1.1.0-2.x86_64
  file /usr/share/icons from install of stacer-1.0.9-2.x86_64 conflicts with file from package netease-cloud-music-1.1.0-2.x86_64
  file /usr/share/icons/hicolor from install of stacer-1.0.9-2.x86_64 conflicts with file from package netease-cloud-music-1.1.0-2.x86_64

Error Summary
-------------

[root@breap Documents]#

**Comment by killerjn** [comment]
have conflicts with several packages
that's why it does not install

**Comment by caramello3469** [comment]
I'm having the exact same issue. I tried installing with DNF instead of YUM. But exact same problem.

**Comment by IzNoGud78** [comment]
I think that to work around the problem, rather than using dnf (or yum), you can try to use the following command:

`sudo rpm -Uvh stacer_1.0.9_x64.rpm --force`

The command does nothing more than force the package to be updated:

- The -U, --upgrade option update the package.
(_Instead of the -U option it is possible to use the -i, --install option which is used to install a package_).

- The -v, --verbose option provides more detailed output

- The -h, --hash option show hash characters during package installation (useful with -v)

The --force option instead is an abbreviation of the --replacepkgs and --replacefiles options that allow to re-install a package if this is already present and to ignore package conflict files.

Unfortunately, the rpm package was removed from the repositories and I couldn't test this method to work around the problem.

**Comment by caramello3469** [comment]
@IzNoGud78 Tried out your workaround. Still doesn't work (Missing dependencies).

error: Failed dependencies:
	libQt5Charts.so.5()(64bit) is needed by stacer-1.0.9-2.x86_64
	libQt5Charts.so.5(Qt_5)(64bit) is needed by stacer-1.0.9-2.x86_64

I tried installing this package, but it installs the 32bit version (Stacer needs the 64bit version).

Also, I noticed the rpm file was removed from the repository. I downloaded it from SourceForge, with the link provided in the Stacer releases page.

**Comment by IzNoGud78** [comment]
@caramello3469 you can specify the architecture of the package that you prefer to install, try to install the package qt5-qtcharts.x86_64 to install the latest 64-bit release of the package.

**Comment by oguzhaninan** [comment]
Sorry about the RPM package problem. For now you can use AppImage. I will fix it and publish it as soon as possible.

**Comment by SingingBush** [comment]
any chance of getting the rpm builds into a repo?

**Comment by oguzhaninan** [comment]
I added RPM package. You can install it as follows.
`sudo rpm --install stacer*.rpm --nodeps --force`

**Comment by dopenw** [comment]
@oguzhaninan Thank you, I installed this software on fedora 28, this works fine

**Comment by ivonenchev** [comment]
1. You need to install qt5-qtcharts - sudo dnf install qt5-qtcharts.
2. Download stacer version 1.0.9 and you can update it with command : 
sudo rpm -Uvh stacer_1.0.9_x64.rpm --force.

Works fine on fedora 28.

**Comment by juliomoraes** [comment]
Hello, just install first:
`sudo dnf install qt5-qtcharts`

**Comment by MKD77** [comment]
> @caramello3469 you can specify the architecture of the package that you prefer to install, try to install the package qt5-qtcharts.x86_64 to install the latest 64-bit release of the package.

it solved.thanks.

**Comment by MKD77** [comment]
> I added RPM package. You can install it as follows.
> `sudo rpm --install stacer*.rpm --nodeps --force`

solved.thanks.
