### ISSUE TITLE
stacer: the order was not found

### ISSUE THREAD

**Issue by killerjn** [oguzhaninan/Stacer#190]
![656](https://user-images.githubusercontent.com/32747059/37568250-89eca750-2aa0-11e8-8789-233cb69fd22f.png)
![5613](https://user-images.githubusercontent.com/32747059/37568274-f00e3530-2aa0-11e8-976d-918738d32ae4.png)
![654645](https://user-images.githubusercontent.com/32747059/37568275-f1be5ec8-2aa0-11e8-81c4-497a8d9c0e24.png)

**did not detect the installation**
after installing I had to turn off the machine

already with that it is fixed

![615156](https://user-images.githubusercontent.com/32747059/37568954-42ad54de-2aaa-11e8-9be4-518c9cb3d87e.png)

# If someone happens after uninstall and update the version turn off your machine

**Comment by oguzhaninan** [comment]
Hi @killerjn ,
I will fix it, thanks for feedback.
