### ISSUE TITLE
After clear logs. Apache is not working

### ISSUE THREAD

**Issue by mhanoglu** [oguzhaninan/Stacer#193]
> Öncelikle uygulama için teşekkürler. İlk sürümlerde denemiştim, mevcut hali gayet başarılı olmuş.

Apache can not create apache2 directory on logs folder. So, this folder musn't be deleted while deleting logs.
> Cannot access directory '/var/log/apache2/' for error log of vhost defined at

Thanks.

**Comment by oguzhaninan** [comment]
Merhaba @marzochi 
Logları silmek kullanıcının sorumluluğunda olan bir durum. Sorun olmayacağından emin olmadığınız dosyaları silmemelisiniz. Bundan önceki sürümlerde (1.0.6 öncesi) uyarı mesajı gösteriliyordu. Mesajı yeni sürümlerde kaldırmıştım. Tekrar ekleyeceğim.

It is the user's responsibility to delete the logs. You should not delete files that you are not sure will be a problem. Earlier versions (prior to 1.0.6) were showing a warning message. I removed the message in the new version. I will add it again.
