### ISSUE TITLE
Dependencies Error ! Help And Fix This Problem !

### ISSUE THREAD

**Issue by KeepWannabe** [oguzhaninan/Stacer#195]
> Help me, if i try installing this package on kali, showing up error like this

[ abdi@eldersc0de.org ]:~/Linux Apps# **dpkg -i Stacer_1.0.4_i386.deb
Selecting previously unselected package stacer:i386
(Reading database ... 375289 files and directories currently installed.)
Preparing to unpack Stacer_1.0.4_i386.deb ...
Unpacking stacer:i386 (1.0.4-1) ...
dpkg: dependency problems prevent configuration of stacer:i386:
 stacer:i386 depends on libgtk2.0-0.
 stacer:i386 depends on libnotify4.
 stacer:i386 depends on libnss3.
 stacer:i386 depends on python.

dpkg: error processing package stacer:i386 (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.3-2+b1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-9) ...
Processing triggers for desktop-file-utils (0.23-2) ...
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 stacer:i386
**
> and then i try with GDEBI, and depend error like this

[ abdi@eldersc0de.org ]:~/Linux Apps# **gdebi Stacer_1.0.4_i386.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: git**

**Comment by oguzhaninan** [comment]
Hi @abdiprawira,
You can install the current version. 
```
sudo add-apt-repository ppa:oguzhaninan/stacer
sudo apt-get update
sudo apt-get install stacer
```

**Comment by KeepWannabe** [comment]
@oguzhaninan 
Hi bro ! 

hmm my distro is kali rolling, not ubuntu

**Comment by oguzhaninan** [comment]
Run this command `sudo apt-get -f install`

**Comment by KeepWannabe** [comment]
just same problem bro, but i done have a git , and the package say dependencies error is git ?

**Comment by oguzhaninan** [comment]
Install this version. [Stacer v1.0.6](https://github.com/oguzhaninan/Stacer/releases/download/v1.0.6/Stacer_1.0.6_i386.deb)
