### ISSUE TITLE
Falied to execute command stacer after installing versin 1.0.9 Ubuntu

### ISSUE THREAD

**Issue by BERA** [oguzhaninan/Stacer#197]
Hi

After installing the update of the package form 1.0.8 to 1.0.9 wasn't successfully completed 

$ sudo dpkg -i stacer_1.0.9_amd64.deb 
(Reading database ... 176902 files and directories currently installed.)
Preparing to unpack stacer_1.0.9_amd64.deb ...
Unpacking stacer (1.0.9-1) over (1.0.8) ...
Setting up stacer (1.0.9-1) ...
Processing triggers for hicolor-icon-theme (0.17-1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...

$ stacer
stacer: command not found

And trying  to start the application form terminal and graphics menu give me the same error: 

Failed to execute command stacer
Failed to execute child process "stacer" (no such file or directory)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by oguzhaninan** [comment]
Hi @Bera,
Can you open it from the Ubuntu launcher, will not it execute at that time?

**Comment by BERA** [comment]
Hi @oguzhaninan 

Trying open it from the Ubuntu launcher I got the same error message. But why after update the executable isn't in the /usr/bin anymore?

**Comment by Bera** [comment]
Hi @oguzhaninan 

The same problem from launcher

**Comment by oguzhaninan** [comment]
Would you uninstall and install again using apt?
``` bash
sudo add-apt-repository ppa:oguzhaninan/stacer
sudo apt-get update
sudo apt-get install stacer
```

**Comment by BERA** [comment]
I uninstalled again and seens work. Thank you @oguzhaninan and sorry for waste your time

**Comment by oguzhaninan** [comment]
You're welcome.

**Comment by wzorroman** [comment]
In my case missed some dependencies, but use this command:
```
$ sudo apt-get install gconf2
$ sudo apt-get install gconf-service
$ sudo apt-get install libappindicator1
```

And then use that @oguzhaninan said:
```
sudo add-apt-repository ppa:oguzhaninan/stacer
sudo apt-get update
sudo apt-get install stacer
```


Reference:
http://aplicacioneslibreuso.blogspot.com/2017/06/como-optimizar-linux-ubuntu-con-stacer.html
