### ISSUE TITLE
Stacer - System Cleaner - bug

### ISSUE THREAD

**Issue by gomes2191** [oguzhaninan/Stacer#198]
System Cleaner during cleanup by removing apache2 and mysql logging folders by breaking the mysql and apache2 package making it uninitiable to boot Deepin 15.5
Affected folders

```
 /var/log/apache2
 /var/log/mysql
```

both folders are being excluded during cleaning
preventing mysql or apache from initializing

Stacer version 1.0.9

**Comment by oguzhaninan** [comment]
https://github.com/oguzhaninan/Stacer/issues/193

**Comment by gomes2191** [comment]
The problem is that it is excluding essential folders for the operation of the applications ie the main log folders destroying the folders would need to run the system this ends up becoming a serious problem.

**Comment by george-cindea** [comment]
the issue is still present in Ubuntu18LTS repos. System cleaner will delete all folders from /var/logs/ when it should delete just the files. Deleting folders makes some services not running, such as apache, mysql and so on
