### ISSUE TITLE
It Can not start up

### ISSUE THREAD

**Issue by tyszwh** [oguzhaninan/Stacer#199]
The wrong message as follows:
stacer

Translator could not load.
ASSERT failure in QList<T>::at: "index out of range", file /opt/qt59/include/QtCore/qlist.h, line 541
[1]    29618 abort (core dumped)  stacer

**Comment by oguzhaninan** [comment]
Hi @tyszwh ,
What is your distribution.

**Comment by tyszwh** [comment]
I use the Ubuntu 16.04

**Comment by oguzhaninan** [comment]
I've been updating the Debian package 2 days ago. Can you try again.

**Comment by tyszwh** [comment]
The problem is still here. 

$ stacer
Translator could not load.
ASSERT failure in QList<T>::at: "index out of range", file /opt/qt59/include/QtCore/qlist.h, line 541
[1]    15292 abort (core dumped)  stacer

**Comment by tyszwh** [comment]
I try both the PPA Repository and stacer_1.0.9_amd64.deb file.
I'm not sure whether this is related to my Qt environment. How can I check it?

**Comment by oguzhaninan** [comment]
Could you write contents of the "/usr/share/stacer/translations/" directory.

**Comment by tyszwh** [comment]
yes. The files included in the directory.
 stracer_ar.qm,stacer_caes.qm,stacer_de.qm,stacer_en.qm,stacer_es.qm,
stacer_fr.qm,stacer_hi.qm,stacer_kn.qm,stacer_oc.qm,stacer_pl.qm,stacer_pt.qm,
stacer_ru.qm,stacer_sv.qm,stacer_tr.qm,stacer_zh-cn.qm

**Comment by hhandoko** [comment]
I have the same problem, on Ubuntu 18.04. Is it anything to do with the user locale, perhaps?

```
$ ls /usr/share/stacer/translations/
stacer_ar.qm     stacer_en.qm  stacer_hi.qm  stacer_pl.qm  stacer_sv.qm
stacer_ca-es.qm  stacer_es.qm  stacer_kn.qm  stacer_pt.qm  stacer_tr.qm
stacer_de.qm     stacer_fr.qm  stacer_oc.qm  stacer_ru.qm  stacer_zh-cn.qm
```

**Comment by ghost** [comment]
Ubuntu 18.04
Tells me "Translator could not load", opens Stacer which works fine but if I choose to continue in the quit menu for the program to continue in the system tray then I can't write more commands on the terminal window from where I launched Stacer. If I quit, then the terminal from where Stacer was launched allows me to write other commands. Nothing major here as the program works but would be great if it wasn't telling me that the translator could not load :).

**Comment by stayprivates** [comment]
Same here, ubuntu 18.04, french.  Install from repository

Translator could not load.
ASSERT failure in QList<T>::at: "index out of range", file /opt/qt59/include/QtCore/qlist.h, line 541
Abandon (core dumped)

Tried "LC_MESSAGES=en_us stacer"  same thing.

**Comment by D4N13L1980** [comment]
Same issue here.
Ubuntu 18.04.1

~$ stacer
Translator could not load.
ASSERT failure in QList<T>::at: "index out of range", file /opt/qt59/include/QtCore/qlist.h, line 541
Aborted (core dumped)

**Comment by axb21** [comment]
Same issue here on Ubuntu 18.04. Any fixes or workarounds?

**Comment by axb21** [comment]
A followup: this issue appears to have been introduced in 1.0.9. I receive the same error with the appimage. However, I can run the 1.0.8 appimage just fine. I have not tried the .deb.

**Comment by axb21** [comment]
This issue has not been corrected in spite of the issue being closed a few days ago.
