### ISSUE TITLE
Apache and mysql error

### ISSUE THREAD

**Issue by manso92** [oguzhaninan/Stacer#20]
When you clean apache2 and mysql  cache, both programs can't starts after next reboot. You need to create again the folder for apache2 and for mysql server you have to run some "hard to find" commands

**Comment by WaKeMaTTa** [comment]
Here is how to fix the problem for MySQL: http://askubuntu.com/questions/760724/16-04-upgrade-broke-mysql-server

**Comment by m1guelpf** [comment]
Are you going to fix this?

**Comment by m1guelpf** [comment]
Is this fixed?

**Comment by oguzhaninan** [comment]
This is not a problem. It is the user's own decision to delete it.

**Comment by manso92** [comment]
I think is a bug. If you clean cache from a program it wouldn't stop working. But the data that the program deletes makes both programs crashes, ergo it is not only caché clean.

**Comment by TristanPapillon** [comment]
I had same bugs, I fixed them by recreate logs dir.
Errors are detailed in syslog (`tail -f /var/log/syslog`).

Apache:
`sudo mkdir /var/log/apache2`

MySQL:
`sudo mkdir /var/log/mysql`
`sudo chown mysql:mysql /var/log/mysql`

On Ubuntu 18, this works for me.

**Comment by simonsp** [comment]
> I had same bugs, I fixed them by recreate logs dir.
> Errors are detailed in syslog (`tail -f /var/log/syslog`).
> 
> Apache:
> `sudo mkdir /var/log/apache2`
> 
> MySQL:
> `sudo mkdir /var/log/mysql`
> `sudo chown mysql:mysql /var/log/mysql`
> 
> On Ubuntu 18, this works for me.

Thanks, works for me.

I had this problem days ago, I formatted my laptop because I couldn't solve it. Today when I installed stacer to do a cleaning the problems started, thanks for the solution.
