### ISSUE TITLE
stacer_1.0.9_x64.rpm missing

### ISSUE THREAD

**Issue by sirredbeard** [oguzhaninan/Stacer#202]
stacer_1.0.9_x64.rpm as referenced in README.md is missing from the Stacer releases page.

**Comment by liberodark** [comment]
Have AppImage

**Comment by sirredbeard** [comment]
1. The rpm is referenced in the documentation and seems to have been generated for each of the previous releases. If rpm support is ending, the documentation should be updated.
2. AppImage is woefully inadequate for applications intended for end users because at a minimum it requires editing permissions, manually installing, and creating custom .desktop entries.

If the AppImage is intended as a replacement for rpm, it is a poor one, and at the very least it should include an install option, e.g. ./Stacer-x64.AppImage --install, which it current does not.

**Comment by Lvaskz** [comment]
This facilitates the integration of appimages on the desktop ( https://github.com/TheAssassin/AppImageLauncher/releases ), there is a rpm package. You do not need to do anything more than install the appimagelauncher.rpm and then double click on the appimage you want and you get rid of thinking. The appimagelauncher integrates the appimage in the application menu, icon, etc.

**Comment by Lvaskz** [comment]
https://translate.assassinate-you.net/projects/appimagelauncher/
Try with this.

**Comment by TheFlagCourier** [comment]
I think it would be much more professional to use an rpm file than rely on a 3rd party AppImage tool. Even switching to FlatPaks or Snaps would be preferable.

**Comment by oguzhaninan** [comment]
I added RPM package. You can install it as follows.
`sudo rpm --install stacer*.rpm --nodeps --force`

**Comment by TheFlagCourier** [comment]
Thanks, @oguzhaninan - Works like a charm on F28.
