### ISSUE TITLE
PPA for Ubuntu 18.04 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by AdamKane41** [oguzhaninan/Stacer#204]
Hey, could we have an update on the PPA at https://launchpad.net/~oguzhaninan/+archive/ubuntu/stacer for Ubuntu 18.04 LTS (Bionic Beaver) pretty please? ;-p

Thanks!

**Comment by oguzhaninan** [comment]
Hi @AdamKane41 
I added package for bionic distribution.

**Comment by AdamKane41** [comment]
@oguzhaninan hmmmm... [Is this right?](https://launchpad.net/~oguzhaninan/+archive/ubuntu/stacer/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic)
![screenshot from 2018-04-27 03-03-50](https://user-images.githubusercontent.com/30092603/39349548-4cbd5df0-49c9-11e8-9ee5-595adcfd7cdf.png)

**Comment by AdamKane41** [comment]
**Fixed**

**Comment by AdamKane41** [comment]
@oguzhaninan 
-PPA For Ubuntu 18.04 works perfect. 
-Stacer 1.0.9-1~bionic runs great.
-A1 !

**Comment by oguzhaninan** [comment]
Thanks !
