### ISSUE TITLE
Works on manjaro?

### ISSUE THREAD

**Issue by federicosnobohm** [oguzhaninan/Stacer#205]
this program works on manjaro gnome?

**Comment by oguzhaninan** [comment]
Hi @federicosnobohm ,
You can use [AppImage](https://github.com/oguzhaninan/Stacer/releases/download/v1.0.9/Stacer-x86_64.AppImage) package.

- Download the AppImage package.
- Run `chmod +x Stacer*.AppImage`
- `./Stacer*.AppImage`
