### ISSUE TITLE
Select All button in System Cleaner

### ISSUE THREAD

**Issue by GowthamPrakaash** [oguzhaninan/Stacer#206]
When select all button is on and if one of the options are turned off, then the select all button must go to off.
![screenshot from 2018-05-12 04-00-29](https://user-images.githubusercontent.com/22129752/39949560-15604c1a-5599-11e8-98d6-65e7eff99f4b.png)

**Comment by oguzhaninan** [comment]
Hi @GowthamPrakaash 
Thanks for feedback. I will fix in the new version.
