### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by balaianu** [oguzhaninan/Stacer#208]
Hello,

I really like Stacer and I use it often, so I would like to help translate it to Romanian.

I tried looking at the translation files in the source, but I wanna ask about the format of the translation files: what can I use to properly open and edit them in order to contribute?

Thanks!

**Comment by oguzhaninan** [comment]
Hi @balaianu,
You can open and edit it with any text editor. You can edit [this file](https://github.com/oguzhaninan/Stacer/blob/native/translations/stacer_en.ts) after rename "stacer_ro.ts".

__Example:__
Before:
```xml
<source>Options</source>
<translation type="unfinished"></translation>
```
After:
```xml
<source>Options</source>
<translation>Opțiuni</translation>
```
