### ISSUE TITLE
Feature request:provide a flatpak 

### ISSUE THREAD

**Issue by Lvaskz** [oguzhaninan/Stacer#210]
Hi, provide a flatpak, the most distros is supported, real time updating. it is great 
See https://flatpak.org/

**Comment by TheFlagCourier** [comment]
Considering Stacer requires running commands as root (via sudo) - and that Flatpaks negate this with their sandboxing (via [bubblewrap](https://github.com/projectatomic/bubblewrap)) - I don't see a feasible Flatpak being adopted.

**Comment by Lvaskz** [comment]
Oh right.
What about snap?

**Comment by TheFlagCourier** [comment]
Snap seems a bit more doable with it's [confinement policy](https://docs.snapcraft.io/reference/confinement) if packaged as classic. I'm unsure if the snap itself is still able to initiate sudo.

**Comment by oguzhaninan** [comment]
Hi @Lvaskz,
For the moment I don't think about adding a snap or flatpak package.
