### ISSUE TITLE
Error starting Stacer 1.0.9

### ISSUE THREAD

**Issue by ezz-amine** [oguzhaninan/Stacer#213]
after the update from 1.0.8 to 1.0.9 the app want start and give the error:

> stacer: symbol lookup error: /usr/share/stacer/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: FT_Property_Set

I like the application and appreciate the effort to make it better, please help me to fix this problem.

**Comment by oguzhaninan** [comment]
Hi @ezz-amine,
Did you try to uninstall the application and install it again?
