### ISSUE TITLE
About] Linux Mint 19 Tara BETA Release

### ISSUE THREAD

**Issue by Wolf-Italy** [oguzhaninan/Stacer#214]
Trying to install stacer_1.0.9_amd64.deb, 
in Linux Mint 19 Tara BETA Release in Testing on Virtual Machines,
the following message appears, see attached screenshot.
---
https://imgur.com/a/JERcn2c
---
Lintian check results for /home/biancospino/Scaricati/stacer_1.0.9_amd64.deb:
warning: --fail-on-warnings is deprecated
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5Charts.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5Core.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5DBus.so.5
E: stacer: arch-independent-package-contains-binary-or-object ... use --no-tag-display-limit to see all (or pipe to a file/program)
---
The software is not installed in any way.

**Comment by oguzhaninan** [comment]
Hi @Wolf-Italy,
Thank you for warning. I will check again when the stable version is released.
