### ISSUE TITLE
Stacer 1.0.9 crashes when installed packages option is selected (Fedora 28, rpm package)

### ISSUE THREAD

**Issue by nikhil-prabhu** [oguzhaninan/Stacer#215]
I'm not sure if this issue is widespread, but whenever I click the packages option in stacer, it crashes (Even the system tray icon disappears). I'm currently running it on Fedora 28 KDE.
![screenshot_20180612_191939](https://user-images.githubusercontent.com/39860598/41294536-e393fbf0-6e75-11e8-8616-fb1b378bb6dc.png)

**Comment by oguzhaninan** [comment]
Hi @nikhil-prabhu ,
Thank you for warning. I've tested it on Fedora 26 and there was no problem. I will fix this problem soon.

**Comment by TheFlagCourier** [comment]
Seems to be working just fine on my end (fresh install of both F28 and Stacer). Possible incompatibility?

![image](https://user-images.githubusercontent.com/2712890/41715466-2b8d0f7e-7519-11e8-9050-8f6cae64b611.png)

**Comment by nikhil-prabhu** [comment]
@TheFlagCourier Mine was a fresh install too (with minimal customization before installing Stacer). But the funny thing is, it seems to be working now (somewhat). It still crashes sometimes, but does work. However, before displaying the list of packages, it displays this (see screenshot). Also, it seems to lag a lot while showing this message, and before actually displaying the packages. So I'm not really sure what's causing this.
![screenshot_20180621_210449](https://user-images.githubusercontent.com/39860598/41729571-29c83a0a-7597-11e8-891e-23900b293cd9.png)

**Comment by TheFlagCourier** [comment]
@nikhil-prabhu Does it do that on every launch? I assumed it would read the packages from cache, if it was available. Also, is your root partition on a solid-state or hard-disk?

**Comment by nikhil-prabhu** [comment]
@TheFlagCourier Yeah, it does that every time I launch Stacer. My root partition is on a solid state (My laptop has an SSD that's 128GB. No Hard Disk).

**Comment by TheFlagCourier** [comment]
Huh... Well, I'm out of ideas. Hopefully this is resolved either in the next update for you, or with normal package updates.
