### ISSUE TITLE
Build Error (QStyle)

### ISSUE THREAD

**Issue by liberodark** [oguzhaninan/Stacer#217]
../../stacer/app.cpp: Dans la fonction membre « void App::init() »:
../../stacer/app.cpp:26:56: warning: « const QRect QDesktopWidget::availableGeometry(int) const » est obsolète: Use QGuiApplication::screens() [-Wdeprecated-declarations]
             size(), qApp->desktop()->availableGeometry())
                                                        ^
In file included from /usr/include/qt/QtWidgets/QtWidgets:58,
                 from /usr/include/qt/QtCharts/QtChartsDepends:5,
                 from /usr/include/qt/QtCharts/QtCharts:3,
                 from ../../stacer/Pages/Dashboard/circlebar.h:5,
                 from ../../stacer/Pages/Dashboard/dashboard_page.h:13,
                 from ../../stacer/app.h:11,
                 from ../../stacer/app.cpp:1:
/usr/include/qt/QtWidgets/qdesktopwidget.h:86:67: note: déclaré ici
     QT_DEPRECATED_X("Use QGuiApplication::screens()") const QRect availableGeometry(int screen = -1) const;
                                                                   ^~~~~~~~~~~~~~~~~
g++ -c -pipe -O2 -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../stacer -I. -I../../stacer-core -isystem /usr/include/qt -isystem /usr/include/qt/QtCharts -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o circlebar.o ../../stacer/Pages/Dashboard/circlebar.cpp
g++ -c -pipe -O2 -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../stacer -I. -I../../stacer-core -isystem /usr/include/qt -isystem /usr/include/qt/QtCharts -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o linebar.o ../../stacer/Pages/Dashboard/linebar.cpp
g++ -c -pipe -O2 -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../stacer -I. -I../../stacer-core -isystem /usr/include/qt -isystem /usr/include/qt/QtCharts -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o startup_app.o ../../stacer/Pages/StartupApps/startup_app.cpp
g++ -c -pipe -O2 -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../stacer -I. -I../../stacer-core -isystem /usr/include/qt -isystem /usr/include/qt/QtCharts -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o startup_app_edit.o ../../stacer/Pages/StartupApps/startup_app_edit.cpp
../../stacer/Pages/StartupApps/startup_app_edit.cpp: Dans la fonction membre « void StartupAppEdit::init() »:
../../stacer/Pages/StartupApps/startup_app_edit.cpp:32:17: error: type « QStyle » incomplet utilisé dans un spécificateur de noms imbriqué
         QStyle::alignedRect(Qt::LeftToRight, Qt::AlignCenter,
                 ^~~~~~~~~~~
../../stacer/Pages/StartupApps/startup_app_edit.cpp:33:56: warning: « const QRect QDesktopWidget::availableGeometry(int) const » est obsolète: Use QGuiApplication::screens() [-Wdeprecated-declarations]
             size(), qApp->desktop()->availableGeometry())
                                                        ^
In file included from /usr/include/qt/QtWidgets/QDesktopWidget:1,
                 from ../../stacer/Pages/StartupApps/startup_app_edit.h:5,
                 from ../../stacer/Pages/StartupApps/startup_app_edit.cpp:1:
/usr/include/qt/QtWidgets/qdesktopwidget.h:86:67: note: déclaré ici
     QT_DEPRECATED_X("Use QGuiApplication::screens()") const QRect availableGeometry(int screen = -1) const;
                                                                   ^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:1327: startup_app_edit.o] Error 1
make[1] : on quitte le répertoire « /tmp/pamac-build-pc/stacer/src/Stacer-1.0.9/build/stacer »
make: *** [Makefile:71: sub-stacer-make_first] Error 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

**Comment by liberodark** [comment]
https://aur.archlinux.org/packages/stacer/#news

**Comment by bthoven** [comment]
Same error here when trying to install it from AUR (I'm using Manjaro Linux).
The dependencies I have for this package are:
```
qt5-*: 5.11.1-1
hicolor-icon-theme: 0.17-1
```
