### ISSUE TITLE
Mint 19, with HiDPI: text truncation

### ISSUE THREAD

**Issue by ghost** [oguzhaninan/Stacer#221]
Screenshot:

![image](https://user-images.githubusercontent.com/9998846/42422044-3e6a5d42-82d7-11e8-9e7d-91ddc9dc424a.png)

System:

X1 Carbon; model number: 20KHCTO1WW
DPI set to: double
Linux Mint 19 x64 Cinnamon
Stacer 1.0.9-1

**Comment by oguzhaninan** [comment]
Hi @CottonEaster,
I can not solve this problem for the moment. Sorry. But soon I will update Stacer, and I will try to solve this problem. [Here](https://github.com/oguzhaninan/Stacer/issues/111) you can follow.

**Comment by luizconrado** [comment]
@oguzhaninan Any update on this topic?
