### ISSUE TITLE
Stacer wont install

### ISSUE THREAD

**Issue by alsoGAMER** [oguzhaninan/Stacer#222]
[root@PC Desktop]# rpm -ivh stacer_1.0.9_amd64.rpm 
Preparing...                          ################################# [100%]
        file / from install of stacer-1.0.9-0.amd64 conflicts with file from package filesystem-3.8-2.fc28.x86_64

Fedora 28
KDE 5
Kernel: 4.17.3-200.fc28.x86_64

**Comment by oguzhaninan** [comment]
Hi @alsoGAMER,
Could you try `sudo rpm --install stacer*.rpm --nodeps --force`

**Comment by alsoGAMER** [comment]
It worked! But why stacer isn't into offcial fedora's repo or in rpm fusion repo?

**Comment by oguzhaninan** [comment]
I will add.
