### ISSUE TITLE
Package does not have a compatible architecture

### ISSUE THREAD

**Issue by didli** [oguzhaninan/Stacer#224]
Weird issue in Fedora 28 x64 with the package stacer-1.0.9-0.amd64.rpm, while I could install the previous version just fine : 
```
Error : Problème: conflicting requests 
- package stacer-1.0.9-0.amd64 does not have a compatible architecture
```
No idea what I'm doing wrong ...

**Comment by oguzhaninan** [comment]
Could you try sudo rpm --install stacer*.rpm --nodeps --force

**Comment by didli** [comment]
Worked right away. For some reason, dnf is not taking stacer-1.0.9-0.amd64.rpm as a proper x86_64 package, so 1.0.8 and 1.0.9 versions are installed side by side, I removed both before installing again and everything seems fine. Thank you !
