### ISSUE TITLE
stacer fonts

### ISSUE THREAD

**Issue by jgw0** [oguzhaninan/Stacer#225]
I am running with ubuntu 18.04

I cannot change the font size in stacer.  I have tried the gnome tweaks and system display but nothing works and I cannot read the text because it is too small.  My screen resolution is 3840x2160 (16:9)

Thank you..................

**Comment by oguzhaninan** [comment]
Hi @jgw0,
I can not solve this problem for the moment. Sorry. But soon I will update Stacer, and I will try to solve this problem. [Here](https://github.com/oguzhaninan/Stacer/issues/111) you can follow.
