### ISSUE TITLE
Arch Linux don't compile

### ISSUE THREAD

**Issue by liberodark** [oguzhaninan/Stacer#226]
Hi

On AUR Stacer won't install : 
make[1]: *** [Makefile:1327: startup_app_edit.o] Error 1
make[1] : on quitte le répertoire « /tmp/pamac-build-pc/stacer/src/Stacer-1.0.9/build/stacer »
make: *** [Makefile:71: sub-stacer-make_first] Error 2
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

Cordialy

**Comment by oguzhaninan** [comment]
Hi @liberodark,
Sorry for delay. I will try compile stacer on arch-linux as soon. I hope I can fix the problem.

**Comment by kannanvm** [comment]
I had a successful build in my arch system. (from source repo (here), not aur)
