### ISSUE TITLE
AppImage does not run on CentOS 7

### ISSUE THREAD

**Issue by shivakumargn** [oguzhaninan/Stacer#227]
The app image throws below error on CentOS 7.5
```
> ./Stacer-x86_64.AppImage 
./Stacer-x86_64.AppImage: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_StacervRs845/lib/libQt5Charts.so.5)
./Stacer-x86_64.AppImage: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_StacervRs845/lib/libQt5Network.so.5)
./Stacer-x86_64.AppImage: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_StacervRs845/lib/libQt5Widgets.so.5)
./Stacer-x86_64.AppImage: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_StacervRs845/lib/libQt5Gui.so.5)
./Stacer-x86_64.AppImage: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_StacervRs845/lib/libQt5Core.so.5)
./Stacer-x86_64.AppImage: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_StacervRs845/lib/libQt5Core.so.5)
./Stacer-x86_64.AppImage: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_StacervRs845/lib/libicui18n.so.55)
./Stacer-x86_64.AppImage: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_StacervRs845/lib/libicuuc.so.55)

```

**Comment by oguzhaninan** [comment]
Hi @shivakumargn,
You can try [rpm](https://github.com/oguzhaninan/Stacer/releases/download/v1.0.9/stacer_1.0.9_amd64.rpm) package to install.

Run `sudo rpm --install stacer*.rpm --nodeps --force` on the downloaded package.
Launch Stacer using the installed `stacer` command.

**Comment by marrypen** [comment]
@oguzhaninan   
I have installed `stacer` exactly via the rpm package, but still got the same error while running `stacer` command.    
How can I get through this? Did I need to recompile since I found a similar issue [here](https://github.com/RocketChat/Rocket.Chat/issues/9829#issuecomment-371487890).

BTW it's CentOS here that the problem occurred.

**Comment by oguzhaninan** [comment]
Could you try this [solution](https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found).

**Comment by shivakumargn** [comment]
I moved from CentOS to Fedora where this problem does not exist. Unable to check on CentOS.

**Comment by ChrisZhangJin** [comment]
also unavailable on CentOs 6. :(
