### ISSUE TITLE
Feature Request: Stacer CLI or Web UI

### ISSUE THREAD

**Issue by stephenjudge** [oguzhaninan/Stacer#228]
I would really like to user Stacer on a remote server as an easy way to keep the server free of cruft. Do you have any plans to offer a lighter CLI version or add a Web UI for remote access?

This was already request but not addressed in a now closed issue: https://github.com/oguzhaninan/Stacer/issues/8#issue-200109264

**Comment by oguzhaninan** [comment]
Hi @stephenjudge,
For remote servers, there are programs ([webmin](http://www.webmin.com/), etc) that have Stacer's features. I made Stacer especially as desktop software. 
Thanks for suggestion and interest. If you have any other suggestions, please share.

**Comment by defcon8** [comment]
+1 webinterface!

**Comment by unclehowell** [comment]
[Firehol Netdata ](https://github.com/netdata/netdata) maybe a bit overkill, but does what's needed.
