### ISSUE TITLE
Pc broken

### ISSUE THREAD

**Issue by Anticolick** [oguzhaninan/Stacer#23]
Hi i've installed your program and i restart my computer i see only login screen and cant log in cant make anything / galiba türksünüz şöyle özeleyeyim programı yükledim daha sonra pcye restart çektim fare hareket ediyor ama tıklamıyor klavye keza aynı şekilde capslock işıgı yanıyor ama tepki yok ekran dondu.  My versiyon is ubuntu 16.04 lts updated

**Comment by oguzhaninan** [comment]
Merhaba, öyle birşeye programın sebeb olma şansı yok ama bilgisayarı güvenli modda başlatıp
`sudo dpkg -r Stacer` komutuyla silip bilgisayarı tekrar başlatıp deneyin

**Comment by Anticolick** [comment]
Çok ilginç sildim oldu

6 Şub 2017 14:12 tarihinde "Oguzhan Inan" <notifications@github.com> yazdı:
