### ISSUE TITLE
Add Clean .Desktop

### ISSUE THREAD

**Issue by liberodark** [oguzhaninan/Stacer#230]
Hi,

In menu libre have possibility to see .desktop broken please add clean for broken .desktop in : 
"/usr/share/applications/my-broken-app.desktop"

Cordialy

**Comment by liberodark** [comment]
have make a solution : https://github.com/liberodark/Linux-Cleaner

**Comment by liberodark** [comment]
But im go to build new software in python :D 
c and c++ is not for me :(

**Comment by oguzhaninan** [comment]
Thanks ! @liberodark

**Comment by m-flak** [comment]
What constitutes a _broken_ .desktop?

You mean desktop files for uninstalled applications still left-behind??

This issue is pertinent to my fork, so please respond. 😀

**Comment by liberodark** [comment]
For what is closed ?
