### ISSUE TITLE
Stacer is very slow!

### ISSUE THREAD

**Issue by FireFoxII** [oguzhaninan/Stacer#236]
On my system with debian buster, Stacer is very slow and is unusable!

When I click on an item on left sidebar, I must attend about 15 second to change the page...

Linux debian 4.18.0-2-amd64 #1 SMP Debian 4.18.10-1 (2018-09-30) x86_64 GNU/Linux
XFCE is my DE

**Comment by m-flak** [comment]
Hey! 👋

Are you comfortable/familiar with Valgrind? If you could run Stacer with Valgrind and post the logs, it'd be amazing.

Here's a guide if you're down. 😀
http://www.valgrind.org/docs/manual/quick-start.html#quick-start.prepare

**Comment by FireFoxII** [comment]
Thanks for helping... This is the log

[stacer.log](https://github.com/oguzhaninan/Stacer/files/2609401/stacer.log)

**Comment by m-flak** [comment]
@FireFoxII How long did you run valgrind for? If you don't remember, could you run it again and mention how long you did it for??

**Comment by m-flak** [comment]
@FireFoxII 
---
Could you retry your luck with the latest upstream? I've PR'ed fixes for the serious memory leaks that I had found. Would you be willing to compile from source and see if the issue's been resolved on your end??

**Comment by FireFoxII** [comment]
Sorry, I haven't seen your reply of 29/11 ... 

Anyway, I have now tested release with new fixes and works perfectly!! Thanks!
