### ISSUE TITLE
Unable to install through PPA

### ISSUE THREAD

**Issue by meetdilip** [oguzhaninan/Stacer#240]
I added the PPA and then tried to update. I got this error

`$ sudo apt-get update
[sudo] password for dilip: 
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:3 http://in.archive.ubuntu.com/ubuntu cosmic InRelease                     
Hit:4 http://security.ubuntu.com/ubuntu cosmic-security InRelease              
Get:5 http://in.archive.ubuntu.com/ubuntu cosmic-updates InRelease [83.2 kB]
Ign:6 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu cosmic InRelease      
Err:8 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu cosmic Release        
  404  Not Found [IP: 91.189.95.83 80]
Hit:9 http://in.archive.ubuntu.com/ubuntu cosmic-backports InRelease
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
When I try the install command, it says **package stacer not found**

Using 18.10

**Comment by chevalier-m** [comment]
Stacer hasn't been ported to Ubuntu cosmic yet, meaning there is no install instructions on the repository for 18.10, thus the `package not found` return message.

**Comment by douglasg14b** [comment]
@mumrau Any notice when it will?

**Comment by chevalier-m** [comment]
I have no idea, I'm not a maintainer, my previous comment was just the result of my analysis.
Nonetheless, I've manually ""backported"" (mind the quotes) the ppa by replacing `cosmic` keyword with `bionic` in source file, and it works well enough for me.

**Comment by PranavBhattarai** [comment]
> I have no idea, I'm not a maintainer, my previous comment was just the result of my analysis.
> Nonetheless, I've manually ""backported"" (mind the quotes) the ppa by replacing `cosmic` keyword with `bionic` in source file, and it works well enough for me.

And how we do that? (newbie)

**Comment by antogerva** [comment]
@PranavBhattrai I believe this is the file to edit:
```
/etc/apt/sources.list.d/oguzhaninan-ubuntu-stacer-cosmic.list
```

**Comment by epexa** [comment]
@mumrau @antogerva **Thanks! It also helped me on Ubuntu 18.10.**

Same problem #259

**Comment by oguzhaninan** [comment]
Hi,
I will release new version soon. I will add new ppa packages.

**Comment by PranavBhattrai** [comment]
> Hi,
> I will release new version soon. I will add new ppa packages.

No, u won't. I think u r very lazy doing ur job.
I don't get any app update because of u.

**Comment by PranavBhattarai** [comment]
> @mumrau @antogerva  I believe this is the file to edit:
> 
> ```
> /etc/apt/sources.list.d/oguzhaninan-ubuntu-stacer-cosmic.list
> ```

But there is nothing on this file or text document.
Are u telling to to rename this "oguzhaninan-ubuntu-stacer-cosmic.list" into "oguzhaninan-ubuntu-stacer-bionic.list" ?
