### ISSUE TITLE
Unmet dependencies [linux mint]

### ISSUE THREAD

**Issue by QwertyMcQwertz** [oguzhaninan/Stacer#241]
when I run 
$ sudo apt-get install stacer
I get the following:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 stacer : Conflicts: stacer:i386 but 1.0.4-1 is to be installed
 stacer:i386 : Depends: libgtk2.0-0:i386 but it is not going to be installed
               Depends: libnotify4:i386 but it is not going to be installed
               Depends: libnss3:i386 but it is not going to be installed
               Depends: libxtst6:i386 but it is not going to be installed
               Depends: python:i386 but it is not going to be installed
               Conflicts: stacer but 1.0.9-1~bionic is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

If anyone can give me a step-by-step solution to this problem, I would greatly appreciate it. I am quite a n00b :/

**Comment by chevalier-m** [comment]
Simply run `apt-get install -dependencies listed-`.

Just like `apt-get install libgtk2.0-0` and so on.
