### ISSUE TITLE
Stacer won't start in Fedora 29

### ISSUE THREAD

**Issue by eggehad** [oguzhaninan/Stacer#245]
Similar to case #139, after install of stacer_1.0.9_amd64.rpm
I get:
****
$ stacer
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
Available platform plugins are: xcb.
Reinstalling the application may fix this problem.
Aborted (core dumped)
****
After reading through the various requests here, I downloaded the appimage which was supposed to fix it: Stacer-x86_64.AppImage

and when I run that, I get:
./Stacer-x86_64.AppImage 
Translator could not load.
ASSERT failure in QList<T>::at: "index out of range", file /opt/qt59/include/QtCore/qlist.h, line 541
Aborted (core dumped)

So I'm dead.  the first method worked perfectly in Fedora 28, but after I upgraded today to Fedora 29, Bah Humbug.

**Comment by oguzhaninan** [comment]
Hi @eggehad,
Thanks for warning. I will release new version soon. I will try fix this problem.

**Comment by eggehad** [comment]
Not fixed.  Today I installed the new version (1.0.9 on FC29):

david@qas console]$ stacer
Translator could not load.
ASSERT failure in QList<T>::at: "index out of range", file /opt/qt59/include/QtCore/qlist.h, line 541
Aborted (core dumped)  

Basically same error as before.
