### ISSUE TITLE
improvement - add icon tray - in hicolor folder theme or in settings to set manually

### ISSUE THREAD

**Issue by erikdubois** [oguzhaninan/Stacer#248]
Could you consider making it possible for users to choose what icon goes in the tray when they want to keep stacer running?
![stacer-tray](https://user-images.githubusercontent.com/10594806/49285290-56e6b780-f497-11e8-9e77-241ab7064364.png)

It is now the only icon that is not white and out of theme.

**Comment by oguzhaninan** [comment]
Hi @erikdubois,
I will add this in new version. Thanks for suggestion.
