### ISSUE TITLE
Use custom title bar for more consistent look

### ISSUE THREAD

**Issue by surajmandalcell** [oguzhaninan/Stacer#25]
Using a custom title bar would be very cool and more consistent as different distros have different themeing and might break the cool dark look.
###### Thanks :)

**Comment by oguzhaninan** [comment]
It was like you said before. But I changed because nobody liked it.

**Comment by surajmandalcell** [comment]
You can use prepros (windows version) like windows decoration...its very professional looking and will look awesome with your dark theme

**Comment by surajmandalcell** [comment]
so it wont be happening i guess?

**Comment by oguzhaninan** [comment]
Sorry. I can not do it this way because of previous problems.
But I will try to do this (https://github.com/oguzhaninan/Stacer/issues/36).
