### ISSUE TITLE
stacer won't load at boot, ubuntu 18.10

### ISSUE THREAD

**Issue by dominusbelial** [oguzhaninan/Stacer#250]
it happens after every fresh start, rebooting just right after power on will fix and load fine. 

when it doesn't run stacer will work if call it from apps menu but it wont display the icon on the top menu.

**Comment by m-flak** [comment]
upload full systemd logs 👈

**Comment by dominusbelial** [comment]
this is the current boot journalctl output, thank you.
[log.txt](https://github.com/oguzhaninan/Stacer/files/2644114/log.txt)

**Comment by dominusbelial** [comment]
this is not happening anymore on my system so i'm closing.
