### ISSUE TITLE
[UX] Light theme: the left app-bar stays dark, add light skin as well 

### ISSUE THREAD

**Issue by breznak** [oguzhaninan/Stacer#255]
Steps to reproduce: 
go to Settigns>Themes choose Light. 
The vertical menu with apps (Dashboard, Startup Apps,... ) remains in a dark mode. 

Expected behavior: 
Vertical menu would also have a light color skin matching the main window. 

Thanks, this app is great!

**Comment by oguzhaninan** [comment]
Hi @breznak,
When i made the menu white, it had never been a beautiful design. But i will try again in the new version.
