### ISSUE TITLE
The text quality option resets after restarting Stacer

### ISSUE THREAD

**Issue by jqadev** [oguzhaninan/Stacer#258]
Hi,

there is a problem with resetting Text quality option in Gnome Settings after restarting Stacer in version 1.0.9.

**Comment by oguzhaninan** [comment]
Hi @jqadev,
Thanks for warning. I am using [Gnome's](https://developer.gnome.org/GSettings/) own tool for settings. I am sorry there is nothing I can do with Stacer for this problem.
