### ISSUE TITLE
Error on launching stacer

### ISSUE THREAD

**Issue by baffled2** [oguzhaninan/Stacer#260]
I installed stacer 1.0.9.1-xenial from the ppa repository, and received no error messages on installation.

However, when I attempt to run it, I get the error message
/usr/bin/stacer: 1: /usr/bin/stacer: Syntax error: ")" unexpected

Running on Mint 18

**Comment by oguzhaninan** [comment]
Hi @baffled2,
Do you get the same error when you try [AppImage](https://github.com/oguzhaninan/Stacer/releases/download/v1.0.9/Stacer-x86_64.AppImage)?

**Comment by baffled2** [comment]
I had exactly the same issue ussing the AppImage

The solution, for me at least, was to go with the Stacer 1.0.6 i386.deb package

maybe the new version is not working with older hardware?
