### ISSUE TITLE
UHD / HighDPI / Retina problems

### ISSUE THREAD

**Issue by Redsandro** [oguzhaninan/Stacer#261]
There is a slight readability error on High DPI monitors. This is on Linux Mint 19.

![image](https://user-images.githubusercontent.com/1702193/53077492-656ec900-34f2-11e9-8b31-41bab8319f81.png)

**Comment by oguzhaninan** [comment]
Hi,
You can follow issue from [here](https://github.com/oguzhaninan/Stacer/issues/111). I want fix this problem but i have not HighDPI monitor. I will try fix this problem soon. Thanks for warning.
https://github.com/oguzhaninan/Stacer/issues/111

**Comment by Deakon997** [comment]
Hello,
I had the same issue but I found a solution for me for Ubuntu 20.04. I start "Stacer" with the following command line:
```env QT_SCALE_FACTOR=0.75 QT_AUTO_SCREEN_SCALE_FACTOR=1 stacer &```
I have fractional scaling set at 150% for my display.
You have to adapt the scaling factors according to your display settings.
Best regards,
Dieter

![Stacer_services](https://user-images.githubusercontent.com/46628797/95862191-cf408400-0d62-11eb-9b42-17ff391cb6ab.png)

**Comment by lilianmoraru** [comment]
@Deakon997 You should not be required to manually set environment variables.
I just made a fix for HighDPI(not sure if or when it will be merged): https://github.com/oguzhaninan/Stacer/pull/418
