### ISSUE TITLE
Feature Request: System Cleaner - Add buttom to select all 

### ISSUE THREAD

**Issue by saymoncoppi** [oguzhaninan/Stacer#262]
Hello Guys!
Congratulations for the really great Job!!!

I wanna share an idea at the System Cleaner tab. 

What do you think to add a button to select all folder on the seccond page. It will make the user life easier

![system_cleaner_page1](https://user-images.githubusercontent.com/22059715/53514319-3e8e3500-3aa6-11e9-9a0f-5dee67da1841.png)
![system_cleaner_page2](https://user-images.githubusercontent.com/22059715/53514320-3e8e3500-3aa6-11e9-9e64-30057a87bc83.png)

See you!

**Comment by oguzhaninan** [comment]
Hi @saymoncoppi,
I will add this feature in the new version.
