### ISSUE TITLE
Doesn't have a release file.

### ISSUE THREAD

**Issue by PranavBhattarai** [oguzhaninan/Stacer#264]
E: The repository 'http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by oguzhaninan** [comment]
Hi @PranavBhattari 
I released the new version.
