### ISSUE TITLE
A heads up

### ISSUE THREAD

**Issue by TheeMahn** [oguzhaninan/Stacer#265]
stacer_1.0.9-1~bionic_all.deb                     Errors=156        Warnings=5        NFO=0                                               
I am writing software that catches errors & automatically fixes it.  Called Repostorm.

E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5Charts.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libQt5Charts.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5Core.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libQt5Core.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5DBus.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libQt5DBus.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5Gui.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libQt5Gui.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5Network.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libQt5Network.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5Widgets.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libQt5Widgets.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libQt5XcbQpa.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libQt5XcbQpa.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libX11-xcb.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libX11-xcb.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libXau.so.6
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libXau.so.6
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libXdamage.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libXdamage.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libXdmcp.so.6
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libXdmcp.so.6
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libXext.so.6
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libXext.so.6
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libXfixes.so.3
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libXfixes.so.3
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libXi.so.6
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libXi.so.6
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libXxf86vm.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libXxf86vm.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libdbus-1.so.3
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libdbus-1.so.3
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libgcrypt.so.20
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libgcrypt.so.20
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libglapi.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libglapi.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libgraphite2.so.3
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libgraphite2.so.3
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libicudata.so.55
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libicudata.so.55
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libicui18n.so.55
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libicui18n.so.55
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libicuuc.so.55
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libicuuc.so.55
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libjasper.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libjasper.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libjbig.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libjbig.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libjpeg.so.8
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libjpeg.so.8
E: stacer: embedded-library usr/share/stacer/lib/libjpeg.so.8: libjpeg
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/liblcms2.so.2
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/liblcms2.so.2
E: stacer: embedded-library usr/share/stacer/lib/liblcms2.so.2: lcms2
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/liblzma.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/liblzma.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libmng.so.2
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libmng.so.2
E: stacer: embedded-library usr/share/stacer/lib/libmng.so.2: libmng
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libpcre.so.3
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libpcre.so.3
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libpng12.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libpng12.so.0
E: stacer: embedded-library usr/share/stacer/lib/libpng12.so.0: libpng
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libselinux.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libselinux.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libstacer-core.a
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libstacer-core.a
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libsystemd.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libsystemd.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libtiff.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libtiff.so.5
E: stacer: embedded-library usr/share/stacer/lib/libtiff.so.5: tiff
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libwebp.so.5
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libwebp.so.5
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libwebpdemux.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libwebpdemux.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-dri2.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-dri2.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-dri3.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-dri3.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-glx.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-glx.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-icccm.so.4
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-icccm.so.4
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-image.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-image.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-keysyms.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-keysyms.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-present.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-present.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-randr.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-randr.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-render-util.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-render-util.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-render.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-render.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-shape.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-shape.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-shm.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-shm.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-sync.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-sync.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-util.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-util.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-xfixes.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-xfixes.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-xinerama.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-xinerama.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxcb-xkb.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxcb-xkb.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxkbcommon-x11.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxkbcommon-x11.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxkbcommon.so.0
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxkbcommon.so.0
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/lib/libxshmfence.so.1
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/lib/libxshmfence.so.1
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/bearer/libqconnmanbearer.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/bearer/libqconnmanbearer.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/bearer/libqgenericbearer.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/bearer/libqgenericbearer.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/bearer/libqnmbearer.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/bearer/libqnmbearer.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqgif.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqgif.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqicns.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqicns.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqico.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqico.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqjp2.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqjp2.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqjpeg.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqjpeg.so
E: stacer: embedded-library usr/share/stacer/plugins/imageformats/libqjpeg.so: libjpeg
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqmng.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqmng.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqtga.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqtga.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqtiff.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqtiff.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqwbmp.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqwbmp.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/imageformats/libqwebp.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/imageformats/libqwebp.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/platforms/libqxcb.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/platforms/libqxcb.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/plugins/xcbglintegrations/libqxcb-glx-integration.so
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/plugins/xcbglintegrations/libqxcb-glx-integration.so
E: stacer: arch-independent-package-contains-binary-or-object usr/share/stacer/stacer
E: stacer: arch-dependent-file-in-usr-share usr/share/stacer/stacer
E: stacer: unstripped-binary-or-object usr/share/stacer/stacer
W: stacer: missing-depends-line
W: stacer: debian-changelog-has-wrong-day-of-week 2018-03-09 is a Friday
E: stacer: extended-description-is-empty
W: stacer: desktop-command-not-in-package usr/share/applications/stacer.desktop stacer
W: stacer: maintainer-script-ignores-errors postinst
W: stacer: maintainer-script-ignores-errors postrm

Just trying to help.

**Comment by TheeMahn** [comment]
I also build Operating Systems:
https://sourceforge.net/projects/ultimateedition/files/

Your application is integrated in, so yes I care.

**Comment by oguzhaninan** [comment]
Hi @TheeMahn 
Thank you for your feedback. I will try fix these problems.
