### ISSUE TITLE
Issue with list of services

### ISSUE THREAD

**Issue by kamov** [oguzhaninan/Stacer#267]
I am using Ubuntu 18.04 with adwaita-dark theme.
the list of services is not readable, check:

![Screenshot from 2019-04-08 15-23-32](https://user-images.githubusercontent.com/2345000/55727521-74fa9080-5a12-11e9-9683-85dbf68b07c8.png)

**Comment by lilianmoraru** [comment]
@kamov What is your resolution?(is it bigger than 1920x1080?)
Might be a duplicate report of #111

**Comment by kamov** [comment]
Yes seem the same issue, my resolution is 4K
Seem there is not a solution yet right?
