### ISSUE TITLE
Proposal: Minimum Ubuntu version support should be Xenial

### ISSUE THREAD

**Issue by lilianmoraru** [oguzhaninan/Stacer#268]
In a few days, Ubuntu 14.04 is EOF.
I propose to Update the Travis build to Xenial and Qt 5.12.2+(ppa).
If Qt 5.12.X LTS is also put as a minimum requirement, then Stacer could load easier compressed images, thus reducing load times and memory consumption.

**Comment by oguzhaninan** [comment]
Hi @lilianmoraru,
Thank you for your suggestion. I think you right. I will update.
