### ISSUE TITLE
Visual feedback for clickable items

### ISSUE THREAD

**Issue by dpizetta** [oguzhaninan/Stacer#270]
I notice some points that could be improved: when clicking to select something need a change in the cursor to the user note that it is clickable. Also, we cannot click on the circles (checks) only in the words, which for me is strange. May something similar to other tabs. See gif. May a duplication of #181 

![stacer](https://user-images.githubusercontent.com/5084939/56769713-676e3600-6788-11e9-8935-0b239398dfc9.gif)

**Comment by oguzhaninan** [comment]
Hi @dpizetta,
I fixed this issue in the new version.

**Comment by dpizetta** [comment]
Nice! Tks

**Comment by Coolest-art** [comment]
Stacer doesn't start on mine VM Linux
