### ISSUE TITLE
Feedback window not working

### ISSUE THREAD

**Issue by dpizetta** [oguzhaninan/Stacer#271]
I've tried to send a feedback with the interface but it says that has an error and we cannot save the message, or try to re-sent or say what is the error.
![stacer-2](https://user-images.githubusercontent.com/5084939/56769820-c03dce80-6788-11e9-85e0-4ae671f560e7.gif)

**Comment by oguzhaninan** [comment]
Hi @dpizetta,
Thank you for warning. I will fix it.
