### ISSUE TITLE
After update, Stacer are installed but is gone.

### ISSUE THREAD

**Issue by tiagojpavan** [oguzhaninan/Stacer#272]
After update from 1.0.9 to 1.1.0, Stacer appears as installed on my system, but don't work, and looking over the system, I won't find it anywhere. Im using a modified Parrot OS version with Ubuntu Xenial Repos, and everything works great after add your repo and install Stacer 1.0.9, but after update to 1.1.0 today, nothing works anymore.
After update, trying to run Stacer from bash I receive a message saying that "Stacer" command wasn't found, even trying run with root privileges.
Uninstalled 1.1.0 using Synaptic and installed old 1.0.9 version using .DEB package, and everything start to work like a charm again.

**Comment by oguzhaninan** [comment]
Hi @tiagojpavan 
After a few hours, update the repository and try again.
`sudo apt remove stacer && apt update && apt install stacer`

**Comment by tiagojpavan** [comment]
> Hi @tiagojpavan
> After a few hours, update the repository and try again.
> `sudo apt remove stacer && apt update && apt install stacer`

OK, I'll try it, Thanks!
Can I make some suggestions here? I'm new to github and don't know where to post suggestions.
It's too much complicated to make Stacer more "friendly" with MATE Desktop Enviroment, like it already are with Gnome? I mean, like use Stacer to change some configs on MATE, I think it will be nice. Oh, I don't know if this is aproblem with Stacer or with my system, or if It's because of MATE, but when Stacer starts with the system, with the "--hide" option activated on startup, it starts but you can't find it anywhere, because the system tray icon won't appear, so I have to force close it using System Monitor, and them start it manually again to see the icon on system tray. And a option to make it minimize directly to system tray will be great. so we don't have to choose to quit or continue whem minimize.
Well, hope this suggestions help in something. If you need beta-tester for this and anything more, tell me, please.

A bir hug and congrats for the amazing work.

Thanks.

**Comment by oguzhaninan** [comment]
Thank you for your feedback. I will try fix it.

**Comment by tiagojpavan** [comment]
Oh! If you need any help translating for Brazilian Portuguese and European Spanish, tell me, ok?

Thanks again
