### ISSUE TITLE
The unselected version of 'do not ask again' looks as if it is selected

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [oguzhaninan/Stacer#273]
This option ('do not ask again') is welcome. However, this:

![image](https://user-images.githubusercontent.com/47056543/57590081-282e3c00-7521-11e9-9373-f20c16bec72d.png)

look somewhat as if it is selected. Does the problem owe to my distro (Mint) or DE (Cinnamon) or theme? Perhaps, in that  hose things could affect the colour. Yet I think that the main problem is the presence of the tick. A tick suggests that something is _on_.

The actual selected image - i.e. what one sees when the option (to not ask again) is enabled - is this:

![image](https://user-images.githubusercontent.com/47056543/57590092-3a0fdf00-7521-11e9-8fcf-6665c5cffdad.png)

Here is a suggestied fix. Have the text say 'Show this dialogue box every time:' and have an on-off radio button or slider.

Stacer 1.1.0.

**Comment by oguzhaninan** [comment]
Hi @LinuxOnTheDesktop 
I will think about it. Thank you for your feedback.
