### ISSUE TITLE
Completely disappeared!

### ISSUE THREAD

**Issue by lbassuncao** [oguzhaninan/Stacer#278]
After install the latest version (1.1.0) on Ubuntu 18.10 (x64) with Gnome 3.30.2. Stacer has disappeared completely from the system! I had previous version (1.0.9) installed. Now I don't have none of them...

**Comment by oguzhaninan** [comment]
Hi @assunluis80,
Could you check `/usr/share/stacer/`folder. If exists restart the system.

**Comment by lbassuncao** [comment]
Hi @oguzhaninan. 
![Stacer](https://user-images.githubusercontent.com/8853276/57654340-d4c4f800-75cb-11e9-91da-cb20170a27a9.png)
![Stacer_2](https://user-images.githubusercontent.com/8853276/57654345-d8587f00-75cb-11e9-9260-a0e9e7d70778.png)
![Uploading Stacer_3.png…]()

**Comment by oguzhaninan** [comment]
Can you download and install [this](https://launchpad.net/~oguzhaninan/+archive/ubuntu/stacer/+files/stacer_1.1.0-1cosmic_all.deb) file after deleting Stacer from the system.

**Comment by lbassuncao** [comment]
Yes. It works after I uninstalled it and then installed the .deb package.
![Stacer_4](https://user-images.githubusercontent.com/8853276/57655228-0d65d100-75ce-11e9-80e5-639ec6e37d73.png)
Thank you @oguzhaninan.

**Comment by oguzhaninan** [comment]
Enjoy the stacer. 😄

**Comment by happydemic** [comment]
I had the same issue with the 1.1.0 package available [via Launchpad](https://launchpad.net/~oguzhaninan/+archive/ubuntu/stacer), but the 1.1.0 .deb in GH Releases installs fine.

On Ubuntu 18.04.
