### ISSUE TITLE
System Tray Icon

### ISSUE THREAD

**Issue by algent-al** [oguzhaninan/Stacer#279]
The program look very cool. Installed it on my machine with Solus 4.0 Budgie.
There is one thing that I don't like.
The icon on system tray is bigger compared to others.

![stacer panel](https://user-images.githubusercontent.com/46356616/57653742-d6de8500-75d2-11e9-9a0f-29638d1e4fcc.png)

**Comment by oguzhaninan** [comment]
Hi @algent-al 
Thank you for your feedback. I will change in the new version.
