### ISSUE TITLE
Feature Request: Appimage installer

### ISSUE THREAD

**Issue by javis** [oguzhaninan/Stacer#280]
now that there isn't an rpm binary for the latest version, we are forced to use the appimage download, which is completely fine, but it won't create an icon to launch the app from the Gnome applications menu.

**Comment by SerdarSaglam** [comment]
I won't use it anymore because there's no rpm package

**Comment by oguzhaninan** [comment]
Hi @TeknoMobil,
I'il add it as soon as possible. Within 2 days.

**Comment by SerdarSaglam** [comment]
Teşekkür ederim Oğuzhan bey

**Comment by oguzhaninan** [comment]
I have added an RPM package. You can [download](https://github.com/oguzhaninan/Stacer/releases/tag/v1.1.0) and install. 
`sudo rpm --install stacer*.rpm --nodeps --force`

**Comment by javis** [comment]
still, it would be good if the appimage could install the icon in the apps menu
