### ISSUE TITLE
provide Stacer v1.1.0_x64.rpm build

### ISSUE THREAD

**Issue by ashishranjan738** [oguzhaninan/Stacer#282]
Why Stacer v1.1.0_x64.rpm build is not available. It would be useful for guys having fedora.

**Comment by oguzhaninan** [comment]
Hi @ashishranjan738 
I have added an RPM package. You can [download](https://github.com/oguzhaninan/Stacer/releases/tag/v1.1.0) and install. 
`sudo rpm --install stacer*.rpm --nodeps --force`

**Comment by ashishranjan738** [comment]
Thanks, @oguzhaninan for making this so fast. :)

**Comment by MarekMaslanka** [comment]
I had a similar issue but with hicolor-icon-theme package and I have resolved it by changing files permissions to 0755 to conflicted files.
