### ISSUE TITLE
Feature request: Any plan to create a snap package?

### ISSUE THREAD

**Issue by alculete** [oguzhaninan/Stacer#285]
Snaps auto updates and can be rolled back if any error appears. I have issues with deb and PPA versions. The alternative is APPIMAGE but I have to always download a new version.

**Comment by VaGNaroK** [comment]
a version of the software in snap and flatpak would already suit all distros this would be a dream.

**Comment by svastian99** [comment]
a question in the same orientation: Any plan to create a flatpak package?

**Comment by alexmyczko** [comment]
An official Debian package is on its way: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946248

Matter of days/weeks/months until it gets through NEW queue http://ftp-master.debian.org/new.html

and archive synced by Ubuntu.

**Comment by Aikatsui** [comment]
![Screenshot from 2020-08-12 09-56-30](https://user-images.githubusercontent.com/63988538/89970064-29996780-dc82-11ea-90d5-06be2e4a65e4.png)

First method seems broken and its quite difficult for manually install the software(dpkg)
Release the app to snap store.

**Comment by oguzhaninan** [comment]
Hi @KizunaH,

No need to add ppa repository for Ubuntu 20+.

`sudo add-apt-repository --remove ppa:oguzhaninan/stacer`

**Comment by oguzhaninan** [comment]
I will not release a Snap package.
