### ISSUE TITLE
Avarage

### ISSUE THREAD

**Issue by willpower232** [oguzhaninan/Stacer#287]
Thanks for the great looking program, my only slight annoyance is the misspelling of average on the `History of CPU Load Averages` section on the `Resources` page.

Not sure if you have already picked it up or if I should make a PR to fix?

**Comment by oguzhaninan** [comment]
Hi @willpower232 
If you want make a PR it would be great. 👍

**Comment by willpower232** [comment]
cheers @jose1711! didn't quite have enough time in my schedule yet :-P

**Comment by jose1711** [comment]
sure @willpower232 - it was the first thing that struck me when I first ran Stacer :smile:
