### ISSUE TITLE
Installing the rpm on fedora 30 returns an error

### ISSUE THREAD

**Issue by notsrijit** [oguzhaninan/Stacer#288]
Error: Transaction check error:
  file / from install of stacer-1.1.0-1.x86_64 conflicts with file from package filesystem-3.10-1.fc30.x86_64

**Comment by oguzhaninan** [comment]
Hi @notsrijit 
I didn't test it on Fedora version 30. 29 working on it. I'm going to test it soon. Thank you for your feedback.

**Comment by ashishranjan738** [comment]
use this command `sudo rpm --install stacer*.rpm --nodeps --force` to install in fedora 30. Its working for me. @notsrijit
