### ISSUE TITLE
[Feature Request] Version Command line Argument

### ISSUE THREAD

**Issue by zero77** [oguzhaninan/Stacer#289]
Can you please add a command line argument like `-v` output `v1.1.0` to quickly show the current version, without having to open Stacer.
Thanks

**Comment by muhammetasan** [comment]
@oguzhaninan  should be closed.

**Comment by oguzhaninan** [comment]
You right @muhammetasan, Thank you for PR.

**Comment by zero77** [comment]
@muhammetasan 
Thanks for the PR but, what is the argument as -v is not working for me.

**Comment by muhammetasan** [comment]
@zero77 have you built on top of native branch?

**Comment by zero77** [comment]
@muhammetasan
I installed it via the PPA Repository
