### ISSUE TITLE
Bash: command not found in Kali Linux

### ISSUE THREAD

**Issue by shakim24** [oguzhaninan/Stacer#296]
After updating and installing stacer in Kali machine I'm unable to run stacer. The stacer file is in my usr directory but when I run the command "stacer" as instructed from the README.md for Debian distro's I get this error BASH: command not found.

**Comment by oguzhaninan** [comment]
Hi @shakim24 
Could you try after restart computer?

**Comment by shakim24** [comment]
Still faced with the same issue even after a reboot. How do I delete the files in usr so I can reinstall the previous version? I never had this issue with the prior version.

**Comment by kdl88** [comment]
Same issues here under Debian 9 and MX Linux 18.3. Command not found. 
Version 1.0.9 works fine.

**Comment by blackoutworm** [comment]
Here's how you fix the problem.
Copy /usr/share/stacer/stacer file to /usr/bin, then install libQt5Charts from the distro repo.
