### ISSUE TITLE
[FIX] Dependencies missing from ppa package and file corrupt

### ISSUE THREAD

**Issue by blackoutworm** [oguzhaninan/Stacer#300]
Hi there. The executable (/usr/bin/stacer) is corrupt, so I had to copy the executable (/usr/share/stacer/stacer) to /usr/bin, and the dependency libQt5Charts is not included in the deb package.
Please fix this. I've seen many people are having problems after the latest update.

**Comment by oguzhaninan** [comment]
Hi @blackoutworm 
Sorry for delay. Thank you for warning. I wil fix this problem.
