### ISSUE TITLE
QObject::setParent: Cannot set parent, new parent is in a different thread

### ISSUE THREAD

**Issue by abc881858** [oguzhaninan/Stacer#309]
https://github.com/oguzhaninan/Stacer/blob/949d9a4d3239a658b0851ac5fe585a48b86980e8/stacer/Pages/SystemCleaner/system_cleaner_page.cpp#L305

please change to:
void SystemCleanerPage::on_btnScan_clicked()
{
//    QtConcurrent::run(this, &SystemCleanerPage::systemScan);
    SystemCleanerPage::systemScan();
}

void SystemCleanerPage::on_btnClean_clicked()
{
//    QtConcurrent::run(this, &SystemCleanerPage::systemClean);
    SystemCleanerPage::systemClean();
}

if not, when the app turn to line 132("ui->lblLoadingScanner->show();"),
error: QObject::setParent: Cannot set parent, new parent is in a different thread

because: 
mLoadingMovie is living in the GUI thread

**Comment by oguzhaninan** [comment]
Hi @abc881858,
Thank you for suggestion. I wil fix this problem in new release?
