### ISSUE TITLE
Best design and usability

### ISSUE THREAD

**Issue by rogercorrea** [oguzhaninan/Stacer#31]
Hi!
I very liked of the your app. The design, buttons, graphics and usability were excellent!
I am curious about the language and libraries your used to development of the interface with the support to Linux.

I read the code and I did see that you used JS but I don't know how you made for compile and transform in executable. I would like to learn. Do you can show me? What did you used?

Thanks!

**Comment by oguzhaninan** [comment]
Thank you.
I used the [electron](https://github.com/electron/electron-quick-start) for the project.

https://github.com/electron/electron-quick-start

**Comment by rogercorrea** [comment]
Thank you, @oguzhaninan!

I thought using your app to learn and add new resources. I can do it?
I can create a script to detect small improvements to the boot system, for example.

**Comment by oguzhaninan** [comment]
Of course.
