### ISSUE TITLE
Canceling authentication from the dialog box when deleting something with System Cleaner displays success message and removes item from list

### ISSUE THREAD

**Issue by zl-kolev** [oguzhaninan/Stacer#310]
Canceling (with the cancel button of the GUI) authentication by the user from the dialog box when deleting something with System Cleaner displays success message and removes entry from list.

Nothing is deleted because the operation is not authenticated by the user but a success message is displayed and the selected item is removed from the list as if it was actually deleted.

IMHO the expected behavior when authentication is canceled (with the cancel button of the GUI) by the user is the item to remain in the list and no message to be displayed.

**Comment by oguzhaninan** [comment]
Hi @zl-kolev,
Thanks you for warning. I wil fix this problem in new release?
