### ISSUE TITLE
System cleaner deletes a folder it shouldn't

### ISSUE THREAD

**Issue by cosmincrihan** [oguzhaninan/Stacer#311]
After running the System cleaner tool, having all cleaning options checked, my system couldn't login at the next restart, and this is because the folder **/var/log/sssd** got deleted by Stacer and the **_sssd_** service failed to start. Stacer should not delete this folder when cleaning the system.

**Comment by PrivateGER** [comment]
Can confirm this with mysql and many other log folders.
Why would you ever delete a log folder if it isn't empty and not restore the original permissions?

**Comment by oguzhaninan** [comment]
Hi @cosmincrihan,
@PerhapsSomeone is right. You are responsible for deleting. Sorry :(
