### ISSUE TITLE
Stacer package is missing for Ubuntu 19.10 "Eoan"

### ISSUE THREAD

**Issue by matheussouza9** [oguzhaninan/Stacer#316]
Trying to install through ppa, it returns the following error

`Err:18 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu eoan Release`
`404  Not Found [IP: 91.189.95.83 80]`

Providing the release name is really required? Some ppa does not require it, like Visual Studio Code.
`http://packages.microsoft.com/repos/vscode stable InRelease`

**Comment by oguzhaninan** [comment]
Hi @matheussouza9 
I didn't release it because I didn't test it on the new ubuntu version. I'il test and release as soon as possible.
