### ISSUE TITLE
Unable to Install on Ubuntu 19.10 (eoan)

### ISSUE THREAD

**Issue by shangles** [oguzhaninan/Stacer#319]
root@Tangles-Ubuntu:/home/chris# add-apt-repository ppa:oguzhaninan/stacer
 Linux System Optimizer and Monitoring
https://github.com/oguzhaninan/Stacer
 More info: https://launchpad.net/~oguzhaninan/+archive/ubuntu/stacer
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://linux.teamviewer.com/deb stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu eoan InRelease                                                                                                          
Hit:3 http://archive.canonical.com/ubuntu eoan InRelease                                                                                                          
Hit:4 http://security.ubuntu.com/ubuntu eoan-security InRelease                                                          
Ign:5 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu eoan InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease                                      
Err:8 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu eoan Release                                   
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by oguzhaninan** [comment]
Hi @shangles 
Its duplicate https://github.com/oguzhaninan/Stacer/issues/316
