### ISSUE TITLE
List of processes. Feature Request

### ISSUE THREAD

**Issue by rdab** [oguzhaninan/Stacer#32]
Hello:
Would it be possible to have a list of processes?. Something similar to the "Processes" tab of Ubuntu's System Monitor.

Thanks. Nice work!

**Comment by oguzhaninan** [comment]
Thank you for your suggestions. I will add it soon.

**Comment by oguzhaninan** [comment]
Hi,
I added the Processes page. [Stacer v1.0.7](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.7)
