### ISSUE TITLE
No CPU speed for non Intel processors

### ISSUE THREAD

**Issue by jgabriel98** [oguzhaninan/Stacer#345]
The field "CPU Speed" is only fullfilled for Intel processors.

![Captura de tela de 2020-01-11 14-42-12](https://user-images.githubusercontent.com/37881981/72208373-a2cca400-3480-11ea-887c-1d0fc12cc32a.png)

Thats how the code in current master branch is:
![Captura de tela de 2020-01-11 14-44-12](https://user-images.githubusercontent.com/37881981/72208404-f808b580-3480-11ea-9e9c-fd433ab2acd5.png)

**Comment by jgabriel98** [comment]
If is from the community interest, i can make a pull request to fix/implements this.

i have it already working on my local branch.

**Comment by oguzhaninan** [comment]
Hi @jgabriel98,
It would be great.

**Comment by jgabriel98** [comment]
> Hi @jgabriel98,
> It would be great.

Thats the final result, it now get the speed from lscpu command.

![stacerClock](https://user-images.githubusercontent.com/37881981/72209140-00192300-348a-11ea-962d-676ceac87eab.gif)

Ignore the current cpu clock, thats for [another issue](https://github.com/oguzhaninan/Stacer/issues/346) (yet related) i was working on.
