### ISSUE TITLE
support for other Linux distro like Fedora, Mageia, OpenMandriva, OpenSUSE, RHEL

### ISSUE THREAD

**Issue by AngryPenguinPL** [oguzhaninan/Stacer#35]
Hi.

I want ask about adding support for other Linux distros like Fedora, Mageia, OpenMandriva, OpenSUSE, RedHat and other. 
Maybe you can simple create .rpm pack for this distro or build it via appimage. Appimage can run on almost all distro (from debian to slackware). So why not?

**Comment by oguzhaninan** [comment]
Hi,
I want to test it properly so that it does not have a problem. I will release it soon.
Thank you for suggesting.

**Comment by alexandru-calinoiu** [comment]
What will you want to test,

I can help out with that.

**Comment by oguzhaninan** [comment]
The AppImage installer is ready.  https://github.com/oguzhaninan/Stacer/releases
But for the time being it works just fine for Ubuntu and Arch Linux. There may be some problems with other distributions.
Soon it will all work fine.

**Comment by probonopd** [comment]
Thanks for the AppImage. Works well for me.

**Comment by AngryPenguinPL** [comment]
Working well as appimage on Ubuntu 16.10. Also I tested it on Fedora 25, Mageia 5 and OpenMandriva LX 3.01 - for all working well but some function in app not work like uninstaller.

**Comment by oguzhaninan** [comment]
Because the system's package installers are different. As I said in the previous comment, it only works fine in "Arch Linux" and "Ubuntu". Soon it will all work fine.

**Comment by aproposnix** [comment]
> Because the system's package installers are different. As I said in the previous comment, it only works fine in "Arch Linux" and "Ubuntu". Soon it will all work fine.

It's not working in Ubuntu 17.04

**Comment by oguzhaninan** [comment]
Hi, 
Do you explain the problem in detail. 
Try the `sudo apt-get -f install` command for the dependency problem.

**Comment by AngryPenguinPL** [comment]
Just trying on Ubuntu 17.10x64. Working like harm without any issue. Maybe could you tell what king of issue you have?

**Comment by aproposnix** [comment]
@oguzhaninan 
The command you provided fixed the issue. I now see the packages in the "Uninstaller" tab when running 17.04. Thanks for that. 

```
~$ sudo apt-get -f install
[sudo] password for somedude: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
