### ISSUE TITLE
Cannot install, repository does not have release file

### ISSUE THREAD

**Issue by ynavott** [oguzhaninan/Stacer#350]
After running `sudo add-apt-repository pa:oguzhaninan/stacer -y` when trying to install stacer I get the follwoing error:
```
Err:12 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu eoan Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
Is this a problem with the repo or am I missing something?
I'm running ubuntu 19.10 with everything updated.

**Comment by alexmyczko** [comment]
once you are on 20.04 (you could upgrade roght now), you can just apt install stacer from the official repo

https://launchpad.net/~gagarin/+archive/ubuntu/eoan/+packages

**Comment by alexmyczko** [comment]
@oguzhaninan i guess you can close this issue as well, and maybe remove references to your PPA? or replace them with mine (comment above)? for people sticking with 19.10 instead of the 20.04 released yesterday
