### ISSUE TITLE
PPA Ubuntu 19.10

### ISSUE THREAD

**Issue by iamnotagentleman** [oguzhaninan/Stacer#354]
Ubuntu 19.10 is out. Will it be supported via PPA ?

**Comment by romainmartinez** [comment]
Same problem here.

**Comment by alexmyczko** [comment]
THIS IS A PPA REPOSITORY https://launchpad.net/~gagarin/+archive/ubuntu/eoan/+packages (Ubuntu 19.10)

you're welcome, although i'd recommend upgrading to 20.04

**Comment by iamnotagentleman** [comment]
@alexmyczko thanks for recommendation but 20.04 is not stable The Ubuntu 20.04 release date is April 23, 2020. daily builds not healthy :)

**Comment by alexmyczko** [comment]
@iamnotagentleman works for me, rock solid since 75 days:  `12:10:34 up 75 days, 20:23,  4 users,  load average: 0.58, 0.62, 0.67`

**Comment by aminelch** [comment]
same here

**Comment by T04435** [comment]
```
Err:14 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu eoan Release                
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                              
E: The repository 'http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu eoan Release' does not have a Release file.
```

I personally will update to 20.04 but it will be good to solve this for users that can upgrade teh dist.

**Comment by oguzhaninan** [comment]
You can use without ppa repository. Just `apt install stacer`

https://github.com/oguzhaninan/Stacer#debian-sid--ubuntu-2004

**Comment by iamnotagentleman** [comment]
@oguzhaninan thanks for your interest 🥇
