### ISSUE TITLE
Can't install it on Fedora 32

### ISSUE THREAD

**Issue by Huluti** [oguzhaninan/Stacer#359]
Here's the message error : 

![image](https://user-images.githubusercontent.com/5782198/78424887-c44cbe80-7670-11ea-8b9a-83f027b55034.png)

**Comment by tester1969** [comment]
Hello, works for me
theodore@teras dumps]$ rpm -qa |grep stacer
stacer-1.1.0-9.fc32.x86_64
[theodore@teras dumps]$ rpm -qa }grep filesystem
filesystem-3.14-2.fc32.x86_64

**Comment by Huluti** [comment]
I didn't know that stacer was in fedora repos. I've installed it from there and it's working. However, I've retried with the rpm file proposed on Github and it keeps showing the error above.

**Comment by tester1969** [comment]
On repos seems newer. Anyway seems just a version conflict, so from repos is just fine.

**Comment by alexmyczko** [comment]
A link to https://repology.org/project/stacer/versions would clarify things?

**Comment by Huluti** [comment]
@alexmyczko it's a good idea!
