### ISSUE TITLE
Breaks Apache2 (and possibly other software)

### ISSUE THREAD

**Issue by TR-SLimey** [oguzhaninan/Stacer#363]
When clearing logs, Stacer removes the log directory, not just the log files. This causes Apache2 to fail on startup with a configuration error, and possibly any other software which relies on their log directories existing.

While it is annoying and a waste of space to have empty directories floating around, it's probably better safe than sorry, hence better to keep them around.

As an alternative, maybe Stacer should delete log directories belonging to packages no longer installed (hence those directories will not be used anymore) though this sounds hard to implement, or give the choice to the user while defaulting to leaving the directories alone and just deleting files.

**Comment by oguzhaninan** [comment]
Hi @TR-SLimey,

https://github.com/oguzhaninan/Stacer/issues/311
https://github.com/oguzhaninan/Stacer/issues/198

**Comment by TR-SLimey** [comment]
If I understand correctly, in the linked issues you are saying this behavior will not change?

I understand that it is the user's responsibility to decide whether to clear logs or not, but for a cleaning program to outright break the system in many cases is clearly a bug which needs to be addressed. Otherwise, what's stopping someone from making a "cleaning" software which wipes the drive completely and then claiming that it is the user's responsibility?

**Comment by oguzhaninan** [comment]
You right @TR-SLimey, But this was not the purpose of the Stacer. This is a feature I added to be used consciously as an extr. I even think about removing it in the future.

**Comment by TR-SLimey** [comment]
Okay. That's understandable. Thanks.

**Comment by oguzhaninan** [comment]
Thanks for your feedback anyway. 👍

**Comment by snex** [comment]
Your attitude about this matter is quite frankly unacceptable, and this bug effectively makes Stacer, an otherwise useful product, a piece of malware. I will be recommending that distros remove it from their package managers, with these Issue tickets as evidence.

**Comment by ghost** [comment]
> Your attitude about this matter is quite frankly unacceptable, and this bug effectively makes Stacer, an otherwise useful product, a piece of malware. I will be recommending that distros remove it from their package managers, with these Issue tickets as evidence.

You are right! After nearly 1 year – no changes. 
I have also just tested Stacer and my system no longer works properly.
@oguzhaninan
