### ISSUE TITLE
Ubuntu 20.04 Release file error

### ISSUE THREAD

**Issue by feeks** [oguzhaninan/Stacer#364]
I am attempting to install Stacer to Ubuntu 20.04 and get the following errors which suggest an release file is required.

Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable Release                                                   
Hit:3 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu focal InRelease                                  
Get:5 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]            
Ign:6 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu focal InRelease                     
Err:7 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu focal Release                       
  404  Not Found [IP: 91.189.95.83 80]
Hit:8 http://archive.ubuntu.com/ubuntu focal-security InRelease
Get:9 http://archive.ubuntu.com/ubuntu focal-updates InRelease [89.1 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [648 B]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,004 B]
Reading package lists... Done          
E: The repository 'http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by zmalter99** [comment]
According to the README.md:

Debian sid / Ubuntu 20.04+
Run as root `apt install stacer`

**Comment by feeks** [comment]
Good day Zach

 

Thank you for the reply. The install was performed as a SUDO account giving me root equivalence. The log entries provided are also run in a SUDO’d process. From my understanding 404 errors are failure to locate file or file existence errors either permissions or physical availability.

 

Cheers

**Comment by loopified** [comment]
There are two instructions for Ubuntu with no clear scope distinction between the first and the second one. Perhaps the first one should indicate up to which release of Ubuntu it refers as it seems the second one is the default fur current release?

**Comment by alkaphreak** [comment]
After adding the Stacer PPA : 
```
sudo apt-get update
...
Err :14 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu focal Release
  404  Not Found [IP : 2001:67c:1560:8008::15 80]
...
sudo apt-get install stacer -y
```
Stacer installed succesfully but it should be interesting to solve those errors.

**Comment by yckbilly1929** [comment]
i faced the same error
installed successfully but the 404 not found is a bit annoying

**Comment by armujahid** [comment]
This issue can be closed because stacer is officially available for focal https://packages.ubuntu.com/focal/stacer and it can be installed without installing any PPA.

**Comment by alexmyczko** [comment]
@feeks can you close the issue?

**Comment by feeks** [comment]
Thank you alex sorry for the tardiness
