### ISSUE TITLE
Issue in Ubuntu 20.04

### ISSUE THREAD

**Issue by cdcsit-maheshyadav** [oguzhaninan/Stacer#365]
Please fix for Ubuntu 20.04

![image](https://user-images.githubusercontent.com/21155192/80338608-70eb1c00-887c-11ea-87b9-8c704133522d.png)

**Comment by oguzhaninan** [comment]
Hi @cdcsit-maheshyadav, Thanks for warning

https://github.com/oguzhaninan/Stacer/issues/364
