### ISSUE TITLE
Starting on OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by alexandru-calinoiu** [oguzhaninan/Stacer#37]
After `npm install`, `npm start` will show the following error in console.

`Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by oguzhaninan** [comment]
I wrote my mistake minus.
 `npm install && npm run build && npm start`

**Comment by alexandru-calinoiu** [comment]
Go it, there a couple of issues with it, but I will report them separately.
