### ISSUE TITLE
Release in Snapcraft

### ISSUE THREAD

**Issue by jj10133** [oguzhaninan/Stacer#370]
Hi, I would like to see the release in snapcraft as it would cover all the linux distros directly rather than releasing for every specific distro

**Comment by alexmyczko** [comment]
Anyone can do a snap, have fun.

**Comment by jj10133** [comment]
@alexmyczko I'm working on it

**Comment by jj10133** [comment]
guys i wanna if the project uses only qt and cmake ?? as i need to know the requirements for making the snap

**Comment by alexmyczko** [comment]
The documentation is at https://snapcraft.io/#
The requirements here: https://sources.debian.org/src/stacer/1.1.0-3/debian/control/

@oguzhaninan I would close this issue.
