### ISSUE TITLE
Release Script not working

### ISSUE THREAD

**Issue by jj10133** [oguzhaninan/Stacer#372]
Running the script file gave the error 

![Screenshot from 2020-05-10 13-44-05](https://user-images.githubusercontent.com/35785259/81507646-6c832200-92c4-11ea-9cd5-540d24d22aef.png)

**Comment by alexmyczko** [comment]
That is an appimage thing, why would you want to create an AppImage, if there's already one? 
https://appimage.github.io/Stacer/

@oguzhaninan I would close this issue.
