### ISSUE TITLE
Stacer Blank Screen - Stacer 1.0.6 amd64

### ISSUE THREAD

**Issue by dmakram** [oguzhaninan/Stacer#38]
![screenshot from 2017-04-03 16-27-36](https://cloud.githubusercontent.com/assets/14863132/24611347/7b85b860-188a-11e7-883a-26850ad6b6ac.png)
![screenshot from 2017-04-03 14-51-14](https://cloud.githubusercontent.com/assets/14863132/24611443/cb0b291a-188a-11e7-83a9-723a2d0983f9.png)

I have tried the latest version of Stacer earlier since this new update seemed interesting but for some reason it opens as a blank screen... This seemed so usual, I tried to delete it manually just in case there was some config file that was making that happen but it isn't the case.
I also tried to uninstalling it using `sudo dpkg -r stacer`, after which I used gdeb to reinstall the application again. I can say I have tried to trouble shoot using the normal simple ideas. But the app still seem so have a problem. I am currently downloading the same version again to see if it was a corruption that might have happened during downloading.

**Comment by oguzhaninan** [comment]
Thanks for your warning. 
I fixed the problem. You can download and install it again.
https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.6
