### ISSUE TITLE
Can you download 'stacer_1.1.0-1bionic_all.deb' ?

### ISSUE THREAD

**Issue by bdh1993** [oguzhaninan/Stacer#380]
I use linux-mint 19.2 tina

> sudo add-apt-repository ppa:oguzhaninan/stacer -y
> sudo apt-get update
> sudo apt-get install stacer -y

I was add PPA repository this stacer and install.
but, Failed error.

http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu/pool/main/s/stacer/

I was direct download this package.
but, download failed.

**Comment by sherlockholmestech** [comment]
try the .AppImage
