### ISSUE TITLE
Bug,  Window going below taskbar and cannot access controls at the bottom of Window

### ISSUE THREAD

**Issue by mick69** [oguzhaninan/Stacer#388]
Bug,  Window going below taskbar and cannot access controls at the bottom of Window

[code]
System:    Host: michael-Compaq-Presario-C700-Notebook-PC Kernel: 5.4.0-40-generic x86_64 bits: 64 
           compiler: gcc v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: Hewlett-Packard product: Compaq Presario C700 Notebook PC v: F.24 
           serial: <filter> Chassis: type: 10 serial: <filter> 
           Mobo: Hewlett-Packard model: 30D9 v: 83.1F serial: <filter> BIOS: Hewlett-Packard 
           v: F.24 date: 01/24/2008 
Battery:   ID-1: BAT0 charge: 4.8 Wh condition: 4.8/4.8 Wh (100%) volts: 10.8/10.8 
           model: Hewlett-Packard Primary serial: N/A status: Full 
CPU:       Topology: Single Core model: Intel Celeron 540 bits: 64 type: MCP arch: Core Merom 
           rev: 1 L2 cache: 1024 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 bogomips: 3724 
           Speed: 1862 MHz min/max: N/A Core speed (MHz): 1: 1862 
Graphics:  Device-1: Intel Mobile GM965/GL960 Integrated Graphics 
           vendor: Hewlett-Packard Presario C700 driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:2a02 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1280x800~60Hz 
           OpenGL: renderer: Mesa DRI Intel 965GM v: 2.1 Mesa 19.2.8 direct render: Yes 
Audio:     Device-1: Intel 82801H HD Audio vendor: Conexant Systems Presario C700 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:284b 
           Sound Server: ALSA v: k5.4.0-40-generic 
Network:   Device-1: Qualcomm Atheros AR242x / AR542x Wireless Network Adapter 
           vendor: Hewlett-Packard driver: ath5k v: kernel port: 3000 bus ID: 01:00.0 
           chip ID: 168c:001c 
           IF: wlp1s0 state: up mac: <filter> 
           Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter 
           vendor: Hewlett-Packard Presario C700 driver: 8139too v: 0.9.28 port: 1000 
           bus ID: 02:01.0 chip ID: 10ec:8139 
           IF: enp2s1 state: down mac: <filter> 
           IF-ID-1: proton0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:    Local Storage: total: 74.53 GiB used: 44.16 GiB (59.3%) 
           ID-1: /dev/sda vendor: Seagate model: ST980811AS size: 74.53 GiB speed: 1.5 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 71.21 GiB used: 21.71 GiB (30.5%) fs: ext4 dev: /dev/dm-1 
           ID-2: /boot size: 703.5 MiB used: 247.0 MiB (35.1%) fs: ext4 dev: /dev/sda1 
           ID-3: swap-1 size: 979.5 MiB used: 523.5 MiB (53.4%) fs: swap dev: /dev/dm-3 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 6 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 1-5:3 info: Realtek USB 2.0 multicard reader type: Mass Storage 
           driver: ums-realtek rev: 2.0 chip ID: 0bda:0158 
           Device-2: 1-6:4 info: Syntek USB 2.0 UVC PC Camera type: Video driver: uvcvideo 
           rev: 2.0 chip ID: 174f:5212 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Device-3: 2-1:2 info: N/A type: Mouse driver: hid-generic,usbhid rev: 1.1 
           chip ID: 0000:3825 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
Sensors:   System Temperatures: cpu: 87.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com tricia main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
           Active apt repos in: /etc/apt/sources.list.d/opera-stable.list 
           1: deb https: //deb.opera.com/opera-stable/ stable non-free #Opera Browser (final releases)
           Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list 
           1: deb [arch=amd64] https: //updates.signal.org/desktop/apt xenial main
           Active apt repos in: /etc/apt/sources.list.d/spotify.list 
           1: deb http: //repository.spotify.com stable non-free
Info:      Processes: 190 Uptime: 8h 51m Memory: 1.44 GiB used: 617.8 MiB (41.9%) Init: systemd 
           v: 237 runlevel: 5 Compilers: gcc: 7.5.0 alt: 7 Client: Unknown python3.6 client 
           inxi: 3.0.32 
[/code]

**Comment by alexmyczko** [comment]
Could you maybe provide a screenshot?

**Comment by mick69** [comment]
Sorry, have removed it
