### ISSUE TITLE
Is the current version of Stacer fully compatible with Ubuntu 20.04.1 LTS?

### ISSUE THREAD

**Issue by mryujitanaka** [oguzhaninan/Stacer#390]
Is the current version of Stacer fully compatible with Ubuntu 20.04.1 LTS? If not, there is some forecast when we will have new updates, since the project has not received new releases since May 2019. Please continue to work on this wonderful project!

**Comment by alexmyczko** [comment]
You're lucky 20.04.* LTS comes with https://packages.ubuntu.com/focal/stacer

I'd like to hear if you find something not being compatible.
