### ISSUE TITLE
There's no ArchLinux / Manjaro AUR package

### ISSUE THREAD

**Issue by sxiii** [oguzhaninan/Stacer#395]
Guys, this is really weird but I cannot find AUR package for Stracer.

Maybe somebody could make one? It would benefit all Arch users.

Thanks. D.

**Comment by IJR222** [comment]
there is now an aur package.

**Comment by sxiii** [comment]
> there is now an aur package.

OMG I was writing "stracer" instead of "stacer", sorry. Now I found it, there are even both -bin and -source versions out there. Nice.

UPD: it works. The only thing I have to do after `pikaur -S stacer-bin` is adding a symlink to /usr/bin/stacer so I can run it with just "stacer" like this: `sudo ln -s /usr/share/stacer/stacer /usr/bin/stacer`

**Comment by IJR222** [comment]
Glad you figured out your issue
