### ISSUE TITLE
Typo Error in uninstaller_page.cpp

### ISSUE THREAD

**Issue by dev117uday** [oguzhaninan/Stacer#396]
There is a typo error in line number **198** and **205** of `stacer/Pages/Uninstaller/uninstaller_page.cpp`

198 : ui->btnUninstall->setText(tr("**Uninstal** Selected (%1)")
205 : ui->btnUninstall->setText(tr("**Uninstal** Selected (%1)")

https://github.com/oguzhaninan/Stacer/blob/native/stacer/Pages/Uninstaller/uninstaller_page.cpp

**Comment by onlycs** [comment]
I created a pull request Thanks
