### ISSUE TITLE
PPA Repo is not working

### ISSUE THREAD

**Issue by ozkansen** [oguzhaninan/Stacer#399]
Hi,

PPA repository is not working -> https://github.com/oguzhaninan/Stacer#ppa-repository-for-ubuntu
i 'm using ubuntu 20.04.1

**Comment by oguzhaninan** [comment]
You don't need PPA repository for Ubuntu 20+. Just run `apt install stacer`
Remove PPA repository `add-apt-repository --remove ppa:oguzhaninan/stacer`

https://github.com/oguzhaninan/Stacer#debian-sid--ubuntu-2004
https://github.com/oguzhaninan/Stacer/issues/364
