### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by 30440r** [oguzhaninan/Stacer#403]
Err:6 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                            
E: The repository 'http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by oguzhaninan** [comment]
Hi @itsrucky 
https://github.com/oguzhaninan/Stacer/issues/399
