### ISSUE TITLE
Stacer command not found

### ISSUE THREAD

**Issue by titamrtn** [oguzhaninan/Stacer#410]
I'm using debian sid and i installed stacer via ` sudo apt install stacer ` and i got stacer 1.1.0-3 installed. And when i try to launch stacer via the terminal i got `command not found: stacer`

**Comment by oguzhaninan** [comment]
Hi @titamrtn,
Would you reboot and run it again.

**Comment by titamrtn** [comment]
I tried and it doesn't work. I also tried to install 1.1.0-1 version and it worked. So i'm gonna keep it for now

**Comment by carolpettirossi** [comment]
I'm facing the same issue... command not found: stacer

**Comment by alexmyczko** [comment]
https://packages.debian.org/sid/amd64/stacer/filelist

maybe something with your $PATH ?

does it start with /usr/bin/stacer ?

**Comment by titamrtn** [comment]
> does it start with /usr/bin/stacer ?

No, stacer not found in /usr/bin also in /usr/local/bin

**Comment by alexmyczko** [comment]
dpkg -l stacer

apt-cache policy stacer

**Comment by titamrtn** [comment]
> dpkg -l stacer
```
sudo dpkg -l stacer
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom            Version      Architecture Description
+++-==============-============-============-=====================================
ii  stacer         1.1.0-3      amd64        Linux system optimizer and monitoring
```
> apt-cache policy stacer
```
sudo apt-cache policy stacer
stacer:
  Installé : 1.1.0-3
  Candidat : 1.1.0-3
 Table de version :
 *** 1.1.0-3 500
        500 http://ftp.univ-pau.fr/linux/mirrors/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by alexmyczko** [comment]
https://packages.debian.org/sid/amd64/stacer/filelist

it clearly is there

apt-get --reinstall install stacer

**Comment by titamrtn** [comment]
> apt-get --reinstall install stacer

It works. Thank you
