### ISSUE TITLE
Ubuntu mate yüklenmiyor

### ISSUE THREAD

**Issue by Natgho** [oguzhaninan/Stacer#42]
Merhaba;
kurulumu ubuntu mate'e yaptığımda şöyle bir hata ile karşılaştım;
`sezer@bozkir:~/İndirilenler$ sudo dpkg --install Stacer_1.0.1_amd64.deb 
(Veritabanı okunuyor ... 341720 dosya veya dizin kurulu durumda.)
Paket açılacak: Stacer_1.0.1_amd64.deb ...
Paket açılıyor: stacer (1.0.1-1) ...
dpkg-deb (alt süreç): arşiv üyesi 'Stacer_1.0.1_amd64.deb' arşivinden kopyalanamıyor: beklenmeyen dosya ya da akış sonu
dpkg-deb (alt süreç): sıkıştırılmış arşiv üyesi açılıyor: lzma hatası: beklenmeyen girdi sonu
dpkg-deb: hata: alt süreç <aç> 2 çıkış kodu ile sona erdi
dpkg: Stacer_1.0.1_amd64.deb arşivi işlenirken sorun yaşandı (--install):
 açılmış './usr/share/Stacer/libnode.so' verisi '/usr/share/Stacer/libnode.so.dpkg-new' konumuna kopyalanamıyor: beklenmeyen dosya ya da akış sonu
Tetikleyiciler işleniyor: bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Tetikleyiciler işleniyor: desktop-file-utils (0.22-1ubuntu5) ...
Tetikleyiciler işleniyor: mime-support (3.59ubuntu1) ...
İşleme sırasında hatalarla karşılaşıldı:
 Stacer_1.0.1_amd64.deb
`

**Comment by oguzhaninan** [comment]
Merhaba
Son sürümü indirip kurmayı dener misiniz?
https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.6

**Comment by Natgho** [comment]
Merhaba, kurulumu son sürüm ile denedim, hata almadım. Stable sürümde problem varmış, teşekkürler.
