### ISSUE TITLE
Distros other than Ubuntu have empty Uninstaller tab

### ISSUE THREAD

**Issue by fethomm** [oguzhaninan/Stacer#43]
Distros other than Ubuntu and Apricity have an empty Uninstaller tab. I have tested with Debian Unstable, Fedora 25, Mageia and Tumbleweed. At least with Debian this does not make sense to me, but I could not find the cause.

**Comment by oguzhaninan** [comment]
Thank you for your interest.
That's the answer. https://github.com/oguzhaninan/Stacer/issues/35#issuecomment-291914272

**Comment by fethomm** [comment]
Thanks,
I am a tech journalist and just finished an article for a german linux print mag on Stacer. So I was curious.
