### ISSUE TITLE
Right Memory Using

### ISSUE THREAD

**Issue by akiffeyzioglu** [oguzhaninan/Stacer#437]
Left side htop, right side Stacer. Which one right?
My PC: Lenovo 330-15IKB 81DE, OS: Mint Cinnamon 20.1 Ulyssa
![image](https://user-images.githubusercontent.com/40912085/108974532-98766500-7696-11eb-9499-5e62be2360f3.png)

**Comment by omerayyildiz** [comment]
@oguzhaninan

**Comment by oguzhaninan** [comment]
Hi @akiffeyzioglu, 
Sorry for the delay, you can find the technical detail here.
https://github.com/oguzhaninan/Stacer/blob/native/stacer-core/Info/memory_info.cpp#L10

For CPU: https://github.com/oguzhaninan/Stacer/blob/native/stacer-core/Info/cpu_info.cpp#L97

**Comment by akiffeyzioglu** [comment]
Thanks.
