### ISSUE TITLE
Newest version doesn't work on Ubuntu 14.04.

### ISSUE THREAD

**Issue by srseven** [oguzhaninan/Stacer#44]
I upgraded to the latest version by downloading the `.deb` file and Stacer has stopped working. It now just shows a black empty screen.

![screenshot from 2017-05-01 02 04 04](https://cloud.githubusercontent.com/assets/9510865/25567991/819759aa-2e12-11e7-97ff-bd7b8ee38b55.png)

**Comment by oguzhaninan** [comment]
Hi, sorry for the problem.
Ubuntu 14.04 has an error because it does not have a `systemctl` tool. You can continue to use the previous version of Stacer. In the new version I will try to fixed the error.
