### ISSUE TITLE
portuguese of portugal translation

### ISSUE THREAD

**Issue by labF212** [oguzhaninan/Stacer#441]
could you update stacer with this file, of translation to portuguese of portugal?
https://github.com/labF212/Stacer/blob/native/translations/stacer_pt-portugal.ts

Paulo Galvão

Thank you for this good program.
Easy to translate...

**Comment by alexmyczko** [comment]
can you create a pull request?

**Comment by labF212** [comment]
Sorry, I m not a programmer. I just edit the file, it was easy to see where to change.
I do not know how to do it.

**Comment by alexmyczko** [comment]
basically this, but you need to fork first and git clone from your fork
```
git clone git@github.com:oguzhaninan/Stacer.git
cp your_stacer_pt-portugal.ts Stacer/translations/stacer_pt-pt.ts
cd Stacer
git status
git add .
git commit -m "add pt-pt translation (gh issue #441)"
git push
```
and then open your fork and click pull request

**Comment by labF212** [comment]
It is not possible only copy the file?

**Comment by alexmyczko** [comment]
@oguzhaninan ?

**Comment by oguzhaninan** [comment]
Thank you for your interest @labF212 and @alexmyczko.
I will update the translation.

**Comment by labF212** [comment]
Ok thks. I will see if that's ok in a new release.
