### ISSUE TITLE
Feature Request: I/O rate visualization

### ISSUE THREAD

**Issue by suurmauri** [oguzhaninan/Stacer#45]
Hey,
first of all: great project! I like it so much that I want to offer a suggestion for a possible new feature:
Would it be possible to have a visualization of current disk I/O activity levels (compare: iotop)?

Regards!

**Comment by xavier83** [comment]
Maybe also **Network I/O per process**. It is the most _missing feature_ in other monitoring tools that I know of.

**Comment by oguzhaninan** [comment]
I added the new version.
