### ISSUE TITLE
CPU Speed Incorect as [Object Object] GHZ under System Info

### ISSUE THREAD

**Issue by CY5** [oguzhaninan/Stacer#47]
Hi,
I'm getting CPU Speed as [Object Object] GHZ under System Info.
I've Downloaded Stacer_1.0.6_i386.deb from [https://sourceforge.net/projects/stacer/files/v1.0.6/](url)
![stacer_01](https://cloud.githubusercontent.com/assets/4632168/26598366/9cd2bdbc-4592-11e7-9602-b4bb6e0d3300.png)

Thanks

**Comment by oguzhaninan** [comment]
Thank you. I will fix it in the new version.

**Comment by oguzhaninan** [comment]
Hi,
I fixed the problem. [Stacer v1.0.7](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.7)
