### ISSUE TITLE
abnormal stacer cpu usage

### ISSUE THREAD

**Issue by milad0123** [oguzhaninan/Stacer#48]
hi.
ubuntu 16.04.2
you can see unusual  stacer procces name and cpu usage at idle:

![gfgfg](https://cloud.githubusercontent.com/assets/19423078/26711530/2c92aa2c-4776-11e7-852c-8b499369b504.jpg)

**Comment by oguzhaninan** [comment]
There is a slight difference due to the transitions.

![stacer](https://cloud.githubusercontent.com/assets/16149251/26727928/26a07c94-47b1-11e7-9423-1b40cd538405.png)
