### ISSUE TITLE
Add to tray

### ISSUE THREAD

**Issue by mixailflash** [oguzhaninan/Stacer#49]
Could you add minimize to tray icon and some infoermation show at tray. It would be very useful.

**Comment by oguzhaninan** [comment]
Thank you for your suggestion.
But there is a better application for system information. [System Load Indicator](https://apps.ubuntu.com/cat/applications/precise/indicator-multiload/)
Most users do not want the tray icon to work.

**Comment by mixailflash** [comment]
System Load Indicator is not the same. It's only system indecation.  But your app is tool to work with packets, if I rigth understand. In tray show icon and some menu to work with app. And this app is very beutiful.

**Comment by oguzhaninan** [comment]
Thank you so much.
I hope I can do what you say in the new version.
