### ISSUE TITLE
Error message when I open Pop Shop in Pop OS! 22

### ISSUE THREAD

**Issue by dnh33** [oguzhaninan/Stacer#496]
The message:

The repository 'https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy Release' does not have a Release file.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details

**Comment by Adithyan007hack** [comment]
Just remove the PPA it don't have a release file for new jammy jellyfish 
You can just install it normally from the official repo

**Comment by dnh33** [comment]
okay thanks
