### ISSUE TITLE
I can't see data visualization of download and upload speed.

### ISSUE THREAD

**Issue by chepegeek** [oguzhaninan/Stacer#5]
Hi, this program look great, but i can't see data of download and upload speed. Try open as root and neither work.

![seleccion_009](https://cloud.githubusercontent.com/assets/13081728/21081049/b897ea12-bf83-11e6-8802-1592a62da09a.png)

**Comment by oguzhaninan** [comment]
Hi, I will fix this and other errors in a few days and publish the new version.
Thank you for your feedback.

**Comment by oguzhaninan** [comment]
I publish a new version.
https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.1

**Comment by chepegeek** [comment]
Great job!, thanks for solved the problem :smile:
