### ISSUE TITLE
"Unistaller" don't work after upgrade v.1.0.6 ("No package found")

### ISSUE THREAD

**Issue by Pablyto** [oguzhaninan/Stacer#50]
I upgrade it by amd64 deb. I use UbuntuGNOME 16.04.
Before upgrade, everything works quite fine, except "system cleaner" ---> "system scan" (don't do nothing, now too).

**Comment by oguzhaninan** [comment]
Hi,
You can try the new version. [Stacer 1.0.7](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.7)
