### ISSUE TITLE
Stacer segmentation fault core dumped

### ISSUE THREAD

**Issue by johnblommers** [oguzhaninan/Stacer#502]
Stacer on PopOS 22.04 built on Ubuntu 22.04 running GNOME and Xorg with 16 GB RAM, 8 cores, AMD APU graphics, ample free storage. It will typically run for a few seconds and then:

```bash
stacer
Gtk-Message: 16:00:50.977: Failed to load module "pk-gtk-module"
Segmentation fault (core dumped)
```

But on a subsequent launch attempt it might work just fine. Then again perhaps this happens:

```bash
stacer
Gtk-Message: 16:04:06.955: Failed to load module "pk-gtk-module"
malloc_consolidate(): unaligned fastbin chunk detected
Aborted (core dumped)
```

**Comment by amiga-500** [comment]
`sudo apt-get install packagekit-gtk3-module`

**Comment by johnblommers** [comment]
Alas I wish it were so simple but that package is already installed:

```bash
sudo apt-get install packagekit-gtk3-module
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
packagekit-gtk3-module is already the newest version (1.2.5-2ubuntu2).
```

At the moment Stacer is running fine and at no time did I make any effort on its behalf except to keep launching it until it took.

**Comment by alexmyczko** [comment]
@johnblommers if it's running now, mind closing the issue?

**Comment by johnblommers** [comment]
Stacer no longer abruptly quits so I'm closing this issue.
