### ISSUE TITLE
Installed Stacer v1.0.7 but nothing happens when I try to open app

### ISSUE THREAD

**Issue by petripanula** [oguzhaninan/Stacer#51]
I uninstalled the Stacer v1.0.7 and took the previous version - that seems to start..

uname -a
Linux ppanula-HP-ZBook-15-G3 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oguzhaninan** [comment]
I fixed the problem. You can install it with the package [stacer_1.0.7_amd64.deb](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.7).

**Comment by petripanula** [comment]
Thanks

-Pete

**Comment by milad0123** [comment]
installed new  deb version on u ubuntu 16.04,but not found in dash menu!
tried to launch from terminal but no result.
it app was in usr/share/applications but could not be run!

**Comment by oguzhaninan** [comment]
Sorry,
I did not update the package at the Sourceforge. I fixed the problem.

**Comment by nicholasli137** [comment]
I have installed new version 1.0.7 on Ubuntu 14.04 today but nothing happened got empty window.

**Comment by BONK1** [comment]
It's working, Thanks a lot:)
