### ISSUE TITLE
Android-like permission management

### ISSUE THREAD

**Issue by martinruenz** [oguzhaninan/Stacer#52]
I wrote down an [idea for an open-source software](https://github.com/mikaelbr/open-source-ideas/issues/34) yesterday and now realised that Stacer might be the right application to integrate such a feature.

I will just copy-paste the feature description here and refer to the link above for more details:

> Sometimes it is useful to employ 3rd-party software (which might be closed source) that you can not fully trust. Currently, there is no user-friendly way – at least that I am aware of – which would allow you to limit the permissions of such an application. Common mobile operating systems offer some form of privilege management, so that the **user can grant permissions, such as accessing contacts, on a per application level**. In my opinion, it would be very convenient and lead to a higher level of security to have an equivalent interface under Linux. After all, **it is an ordinary wish to use closed-source software, but I don’t think providing access to all personal files is the best default behaviour**.
> 
> Of course, the system architecture of a mobile OS differs greatly from the one of a Linux desktop. But I think that [AppArmor](http://wiki.apparmor.net/index.php/Main_Page) profiles could be managed by a GUI to yield a similar user experience. 
> 
> Here is a rough mockup of how the controls for a single application could look like:
> 
> [![mockup_s](https://user-images.githubusercontent.com/303783/27012196-759d1a14-4ec3-11e7-80ac-744dfc5fd74f.jpg)](https://user-images.githubusercontent.com/303783/27012169-ca8dcd9e-4ec2-11e7-88b8-72ce28638cee.jpg)

**Comment by oguzhaninan** [comment]
Hi,
Great idea. I will try to make it.
