### ISSUE TITLE
Can not add PPA

### ISSUE THREAD

**Issue by robouden** [oguzhaninan/Stacer#520]
On Linux Mint, I get the message “Cannot add PPA: 'This PPA does not support jammy'”.
Any updates for that?

Regards,
Rob Oudendijk

**Comment by alexmyczko** [comment]
which version of linux mint? which ppa?

**Comment by robouden** [comment]
Linux mint 21.1. But I found the deb that worked fine. So we can close the issue.

Regards,
Rob Oudendijk
