### ISSUE TITLE
Extremely long loading time on app startup

### ISSUE THREAD

**Issue by justinnichols** [oguzhaninan/Stacer#53]
**OS**: Ubuntu 16.04.2 LTS
**`uname -a`**: Linux hostnamehere 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**Installed version**: stacer_1.0.7_amd64.deb

I realize there is a TON of information being gathered on startup which I suspect has a lot to do with this.  The application startup time from launching the window to seeing some output aside from "Loading" is very long, on the order of 2 minutes, 11 seconds.

**Comment by oguzhaninan** [comment]
Hi,
It just happened once. Or does it happen every time? 
Could you send `~/.config/Stacer/stacer.log` file ?

**Comment by justinnichols** [comment]
Every time I launch.  I've tried clearing out the .config/Stacer and trying again, same result.  The contents of the `~/.config/Stacer/stacer.log` is small:

```
{"meta":"","level":"error","message":"Uninstaller Get Packages","timestamp":"2017-06-12T17:23:01.176Z"}
{"meta":"","level":"error","message":"Uninstaller Get Packages","timestamp":"2017-06-12T17:27:29.273Z"}
{"meta":"","level":"error","message":"Uninstaller Get Packages","timestamp":"2017-06-12T17:33:59.711Z"}
```

**Comment by oguzhaninan** [comment]
There is no solution other than removing and reinstalling. Load time is fixed, it should be finished in 2.5 seconds. A mistake that should not be. I am really sorry.

**Comment by justinnichols** [comment]
No need at all to be sorry :) I will completely remove and reinstall via dpkg and see how it fares.  I will reply with the results asap.

**Comment by justinnichols** [comment]
I should note that I am on a full drive encryption disk (using LUKS I believe).  I know that can sometimes cause headaches for system-level utilities like this.

I re-downloaded the .deb and ran all of the following; sadly the startup time is still long:

```
$> sudo dpkg -r stacer
[sudo] password for myuser: 
(Reading database ... 414848 files and directories currently installed.)
Removing stacer (1.0.7) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...

$> rm -rf ~/.config/Stacer

$> sudo dpkg -i ~/Downloads/stacer_1.0.7_amd64.deb
Selecting previously unselected package stacer.
(Reading database ... 414772 files and directories currently installed.)
Preparing to unpack ./stacer_1.0.7_amd64.deb ...
Unpacking stacer (1.0.7) ...
Setting up stacer (1.0.7) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...

$> stacer
```

**Comment by oguzhaninan** [comment]
Thank you.
It might be what you say. I'm going to investigate.
Have you used any of the previous versions?. Does such an issue happen in previous versions?

**Comment by justinnichols** [comment]
I'm sorry, this is my first try with Stacer.  I will attempt a previous version to see how it goes as well.

**Comment by justinnichols** [comment]
v1.0.6 also exhibited the same very long load time issue except it was with a white screen instead of the "Loading" screen.  I have forked the code to try to help see what this can be.  I have some experience with electron (minimal, though) and can work through javascript.

**Comment by oguzhaninan** [comment]
Can you build from source and look at the project.  https://github.com/oguzhaninan/Stacer#build-from-source

**Comment by justinnichols** [comment]
Yup, giving it a go now.

**Comment by justinnichols** [comment]
Verified running via source code still exhibits the long load time (well beyond the 2500 millisecond timeout in the `mounted()` function.  It almost feels as if that function isn't getting ran until considerably later.  I'm going to attempt to runtime debug.

**Comment by oguzhaninan** [comment]
Would you look at the *console* errors.

**Comment by justinnichols** [comment]
Don't seem to be any errors on the command line or in the web console after I added the following in `main.js` `createWindow()` between line 36 and 38 (just before the `win.on('closed' ... )`:

`win.webContents.openDevTools()`

**Comment by justinnichols** [comment]
It's strange, when I breakpoint into the mounted() function, it's as if it won't get into it for that long period of time and everything is stalled.  This is the first electron app I've used with this issue (I run Slack, Wire Desktop, IRCCloud, etc).

**Comment by oguzhaninan** [comment]
When you remove the [line](https://github.com/oguzhaninan/Stacer/blob/master/src/index.js#L34) and try it, there is problem ?

**Comment by oguzhaninan** [comment]
Try changing the mounted() function to created().

**Comment by justinnichols** [comment]
The problem persists after commenting out that line and changing it to `created()` instead.  This is what shows for those two minutes and then the animation shows (and if the setTimeout line is active it will then show the dashboard 2500 milliseconds later):

![stacer_loading](https://user-images.githubusercontent.com/2378678/27052580-1b43e06e-4f88-11e7-8984-7a52fb8d3a36.png)

**Comment by oguzhaninan** [comment]
Is the program locked or is it okay when you try to delete the [lines](https://github.com/oguzhaninan/Stacer/blob/master/src/components/App.js#L82-L94)?

**Comment by justinnichols** [comment]
I'm going down the same path you are in troubleshooting :)  I'm feeling like it's something in the `config()`, but not positive, still shooting in the dark.

The app did lock up after removing that whole `<div id="loading">`.  I didn't wait the whole two minutes before killing the process.

**Comment by justinnichols** [comment]
To note: When that `<div>` is there and the Loading screen shows (but no animation), the app isn't locked.  I can click the X to close it.

**Comment by justinnichols** [comment]
I take it back, `config()` doesn't seem relevant, because that code is completely passed prior to the stall-out when breakpoint debugging.  It's something in between `beforeCreate()` and `mounted()`.  I'm not sure if it's this vue.js or not.

**Comment by oguzhaninan** [comment]
Finally, do you remove the _mounted()_ function from the _index.js_ and append it to the _App.js_ file.

**Comment by justinnichols** [comment]
Sadly the same problem.  This is very strange.  I can try to keep at this.  If I'm the only one exhibiting this issue right now then either a) It's localized to only my machine; or b) It has something to do with being on an encrypted disk; or c) I'm running into some Vue.js issue that Googling hasn't uncovered; or d) I'm crazy!

I will update this ticket _(even if you close this ticket as cannot reproduce)_ if I happen to figure anything out.  I don't want to keep you diving into something that isn't widespread yet.

Thank you so much for all your help today!

**Comment by oguzhaninan** [comment]
I thank you very much. You've been very helpful.

**Comment by justinnichols** [comment]
Okay I found the culprits, but do not know yet the fix.

In `components/dashboard/Dashboard.js`, after commenting out the `<down-bar/>` and `<up-bar/>`, and in `components/resources/Resources.js`, after commenting out the `<network-history>` container, the app loads up just fine as expected (loading animation, then 2.5 seconds later, the dashboard).

So this has something to do with getting information about my network interfaces.

**Comment by justinnichols** [comment]
So it looks like it's this particular call that is taking an extremely long time on my system:
```
route 2>/dev/null | grep default | awk '{print $8}'
```

That is found in https://github.com/sebhildebrandt/systeminformation/blob/master/lib/network.js#L35

**Comment by justinnichols** [comment]
I am so sorry for this and for possibly wasting your time.  It turns out it has to do with that `route` call taking a long time to return due to /etc/resolve.conf having a search domain added due to being on a VPN.  I'm not sure there is anything you can do on this application to fix this.  I believe it may have to do with that search domain being added erroneously (it's an old domain of theirs) and I'll need to contact my VPN provider about it.

**Comment by justinnichols** [comment]
FYI for posterity, turning off Automatic DNS on the VPN connection in Linux also solved this.

**Comment by oguzhaninan** [comment]
I really appreciate your effort. Thank you very much for solving the problem.
If I can find a solution for this, I can prevent the problem from happening in the new version.
Thanks.
