### ISSUE TITLE
Blank Black screen on startup

### ISSUE THREAD

**Issue by alien0304** [oguzhaninan/Stacer#55]
Blank Black screen on startup. Installed from Deb 64 package

**Comment by oguzhaninan** [comment]
Hi,
Could you send ~/.config/Stacer/stacer.log file ?

**Comment by alien0304** [comment]
no log file

**Comment by oguzhaninan** [comment]
Will you try `stacer-1.0.7-x86_64.AppImage`.

**Comment by alien0304** [comment]
same thing blank black on startup.  i am using Cinnamon DE if that matters

**Comment by oguzhaninan** [comment]
Ubuntu release ?

**Comment by alien0304** [comment]
Ubuntu 14.04 unity, but i use cinnamon DE

**Comment by oguzhaninan** [comment]
Ubuntu 14.04 not suitable for Stacer. There are many problems like this.https://github.com/oguzhaninan/Stacer/issues/44  I'm sorry for the problem. I will do whatever it takes to fix it in the next release.
