### ISSUE TITLE
Stopped loading when dpkg is missing

### ISSUE THREAD

**Issue by blackPantherOS** [oguzhaninan/Stacer#69]
Hi! When dpkg does not available on system the main window is still white . 

![image](https://user-images.githubusercontent.com/12883566/27284597-b2095648-54f9-11e7-8e53-8d05779527a5.png)

**Comment by oguzhaninan** [comment]
I fixed the problem. You can try the [new version](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.8).

**Comment by blackPantherOS** [comment]
Thank You! We will do test with new version
