### ISSUE TITLE
Not loading UI since last update installed

### ISSUE THREAD

**Issue by rayediaz** [oguzhaninan/Stacer#71]
![screenshot from 2017-06-21 12 28 18](https://user-images.githubusercontent.com/15975670/27395279-437734f4-567d-11e7-8c60-7633af088f3b.png)

**Comment by oguzhaninan** [comment]
Hi,
What is your distribution ?
If you have the "~/.config/Stacer/stacer.log" file please send me. And run `rm -r ~/.config/Stacer`

**Comment by rayedpg** [comment]
I've deleted `~/.config/Stacer` multiple times before and also reinstalled the app but I don't know what's going on.  

Here you have the `stacer.log` file.
[stacer.log.zip](https://github.com/oguzhaninan/Stacer/files/1093263/stacer.log.zip)

**Comment by oguzhaninan** [comment]
That's the reason for your problem. https://github.com/oguzhaninan/Stacer/issues/55#issuecomment-308251972 https://github.com/oguzhaninan/Stacer/issues/44#issuecomment-298310770
I will soon release an update that will fix this problem.

**Comment by rayediaz** [comment]
Hi,
After reading #56 comments, I got it to work as well by installing "systemd". 

`sudo apt-get install systemd -f`
 
Not errors, everything's perfect. 
Thanks!
