### ISSUE TITLE
Bug: Resize window on Linux

### ISSUE THREAD

**Issue by hiseni** [oguzhaninan/Stacer#73]
Hey!

Nice app :slightly_smiling_face:
but I cant use it on my 11'6 inch laptop running Linux Mint 18.

The window is too big and action buttons are not accessible
and I can not resize it.

Please, fix this if you can :pray: 
I want to use this :smiley: 

Screenshot attached.
![screenshot from 2017-06-25 16-03-24](https://user-images.githubusercontent.com/8407846/27516331-93e31a66-59c0-11e7-9c06-33759a3bfae9.png)

**Comment by oguzhaninan** [comment]
Hi,
Sorry for the problem. The new version will be responsive. I will publish soon. 
Thanks for the feedback.

**Comment by oguzhaninan** [comment]
I fixed the problem. You can try the [new version](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.8).
