### ISSUE TITLE
Support for more than 8 CPU cores

### ISSUE THREAD

**Issue by Libbum** [oguzhaninan/Stacer#76]
Probably best to implement the display of N threads rather than a set number.

Problematic example:
![2017-07-04-193905_3440x1440_scrot](https://user-images.githubusercontent.com/3059508/27839370-f6a9bd44-60f0-11e7-9253-175e37330381.png)

**Comment by interlock** [comment]
Related to this, but there is some jitter in the cpu labels UI when you get to > 6 threads as well. Given the app forces fixed size window, may as well div that up by 4 to 6 per row.

**Comment by joeykrim** [comment]
Attempted to help and added colors for up to 20 cores, the most I can confirm are visually distinct: https://github.com/oguzhaninan/Stacer/pull/94
