### ISSUE TITLE
apt-get install for Ubuntu

### ISSUE THREAD

**Issue by binarykitchen** [oguzhaninan/Stacer#77]
Would be great if we can apt-get install that on Ubuntu too... thx

**Comment by Binaryify** [comment]
just double click the deb installer file

**Comment by binarykitchen** [comment]
Yeah I know but then, with .deb files it won't update. Using `apt-get update` is a lot more convenient.

**Comment by Daniel15** [comment]
The maintainers could create a Debian repo using Aptly and then publish it to any static file host (like S3 or even just GitHub Pages)... That's what we do for [Yarn](https://yarnpkg.com/).

**Comment by joeykrim** [comment]
Similar to the PPA request: https://github.com/oguzhaninan/Stacer/issues/36

**Comment by PyroSamurai** [comment]
launchpad is also an option

**Comment by ghost** [comment]
.deb is much more better , for installation . Instead add a notification in the application , when your application updates to a new version .
