### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kucukkanat** [oguzhaninan/Stacer#8]
Being able to use this for remote ubuntu servers would be awesome via ssh or a server-client fashion

**Comment by HornyakBence** [comment]
Detailed info's for CPU, Memory and Disk usage would be super cool. 
I didn't want to open a new Feature request, so just wrote it here.

**Comment by tauxeta** [comment]
I second what _HornyakBence_ said, real time Disk, Ethernet/Wifi/network traffic, I/O and Process-viewer, please.

**Comment by ur1katz** [comment]
tauxeta my pull request adds some info about disk,  cpu and memory.  I would love to get some comments on it. What extra info would you like to see?

**Comment by mone27** [comment]
adding a screen showing running processes(similar to gnome-system-monitor) would be awesome!

**Comment by oguzhaninan** [comment]
Hi,
I added the Processes page. [Stacer v1.0.7](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.7)

**Comment by mone27** [comment]
Sorry, I installed Stacer this morning and I didn't see the development of Stacer 1.0.7.

**Comment by oguzhaninan** [comment]
I published it after your comment.
