### ISSUE TITLE
Can clean package apps using "select all"

### ISSUE THREAD

**Issue by SalahAdDin** [oguzhaninan/Stacer#81]
I'm using `Stacer` for cleaning the system, but i have a bug:
![deepin-screen-recorder_stacer_20170706124003](https://user-images.githubusercontent.com/5034215/27905405-79dab30a-6248-11e7-9579-8e84046fb789.gif)
As you can see, if i do click in select all, it doesn't works, but is i select one by one, it works, why?

**Comment by oguzhaninan** [comment]
I fixed the problem. You can try the [new version](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.8).
