### ISSUE TITLE
Stacer 1.0.7 for Fedora as RPM download link broken. [Sourceforge]

### ISSUE THREAD

**Issue by muhammadahmadmujtaba** [oguzhaninan/Stacer#83]
Unable to download Stacer v1.0.7 .rpm package for Fedora. Download link to sourceforge is broken.
Connection gets disturbed while downloading package.

**Comment by oguzhaninan** [comment]
I've just tried it and I've never had a problem. You had trouble with Github.

**Comment by muhammadahmadmujtaba** [comment]
I tried it again. Download starts but It just don't get ahead and connection breaks.
I tried using Fedora 25.
I am now using Linux Mint 18.2.
Nothing working. Is it because of mirror for Asia?
We have submarine line issue for South Asian countries.

**Comment by oguzhaninan** [comment]
Do you use VPN?

**Comment by muhammadahmadmujtaba** [comment]
no. I do not.

**Comment by muhammadahmadmujtaba** [comment]
are there mirrors available?

**Comment by oguzhaninan** [comment]
Try downloading using this tool. [axel](https://www.tecmint.com/axel-commandline-download-accelerator-for-linux/)

Run `axel https://10gbps-io.dl.sourceforge.net/project/stacer/v1.0.7/stacer-1.0.7.rpm`

**Comment by muhammadahmadmujtaba** [comment]
it worked. thank you.
