### ISSUE TITLE
Not working for elementary os

### ISSUE THREAD

**Issue by c0b41** [oguzhaninan/Stacer#85]
![ekran goruntusu - 2017-07-08 16 23 01](https://user-images.githubusercontent.com/2834954/27985749-399de65a-63fa-11e7-855d-5d98fe626789.png)

**Comment by oguzhaninan** [comment]
Would you give me the output of this command.
`systemctl list-unit-files --state=enabled,disabled --type=service`

**Comment by c0b41** [comment]
@oguzhaninan loki or freya?

**Comment by oguzhaninan** [comment]
loki

**Comment by c0b41** [comment]
@oguzhaninan seems like freya not support systemctl
