### ISSUE TITLE
Disk status not updating on extend

### ISSUE THREAD

**Issue by 29axe** [oguzhaninan/Stacer#89]
Hi,
I'm using stacer on a VirtualBox machine running Ubuntu Gnome 17.04.
However after a partition resize from 17.9GB to 60GB, the Stacer Dashboard still shows 17.9GB instead of 60GB. I extended the drive size from VirtualBox command line utility and then extended the LVM partition using gparted.
Could it be a bug in stacer?

**Comment by oguzhaninan** [comment]
Hi,
Will you give the output of the `df -lkPT`

**Comment by 29axe** [comment]
Hi,
Apparently this was my mistake and has nothing to do with Stacer. df command returned 17GB too. So I used gparted livecd to properly extend partition using these 2 commands :
- lvextend
- resize2fs

Now Stacer shows the desired size.

Thanks for the tip and sorry for posting this unrelevant issue.
