### ISSUE TITLE
System Cleaner not working on Ubuntu 17.04

### ISSUE THREAD

**Issue by falconxxx** [oguzhaninan/Stacer#90]
I installed stacer recently and everything works fine except the system cleaner,
Clicking on the system scan button won't show anything or perform any action.

![image](https://user-images.githubusercontent.com/9302799/28153937-f7c5a502-679f-11e7-93e9-e221dc3aeaf5.png)

**Comment by oguzhaninan** [comment]
Hi,
Do you choose from the left menu.

**Comment by falconxxx** [comment]
Yes I chose the system cleaner from the left menu

On Jul 13, 2017 8:04 AM, "Oguzhan Inan" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,
Do you choose from the left menu.

**Comment by oguzhaninan** [comment]
- Package Cache
- Crash Reports
- System Logs
- App Cache
- Trash
 have you selected one of these?  You seem to be unselected in the picture.

**Comment by oguzhaninan** [comment]
I fixed the problem. You can try the [new version](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.8).

**Comment by RAJUPROP** [comment]
I have the same problem installing Stacer in Ubuntu 16.04. (with both ver 1.0.8 and 1.0.9.) The software is installed on Ubuntu , but when we click on the program icon , nothing happens. Terminal access is also unsuccessful. (same issue with my Laptop also , Ubuntu 16.04 LTS). I installed Stacer on another desktop PC having Ubuntu 16.04 , however , the same result.....

**Comment by may215** [comment]
Same issue here, I have the latest version.
