### ISSUE TITLE
Greek Translation

### ISSUE THREAD

**Issue by JordanKostelidis** [oguzhaninan/Stacer#92]
Hi, i will create a Greek Translation for Stacer !

**Comment by oguzhaninan** [comment]
Hi,
You can start to translate this [file](https://github.com/oguzhaninan/Stacer/blob/master/src/languages/langs/lang.en.js).
Thank you !

**Comment by ghost** [comment]
I have translated the files for 2 branches (native and electron)
Download it from here
https://github.com/JNKSoftware/StacerGreekTranslation
