### ISSUE TITLE
Visibility for multiple disks

### ISSUE THREAD

**Issue by joeykrim** [oguzhaninan/Stacer#95]
Only able to view one disk when other disks (NVME, HDD, SDD) are installed, screenshot below.
A few helpful ideas:
A method to swap between disk usage, such as clicking on the disk widget, would be good.
A method to identify the different disks, such as the mount path or /dev location, would be good.

Current view - only displays one disk
![image](https://user-images.githubusercontent.com/208641/28497641-dc0d4916-6f40-11e7-961d-0c1f22d40d43.png)

**Comment by oguzhaninan** [comment]
Hi,
The disk where the system is installed is displayed. I will make a detailed page for disk use.
