### ISSUE TITLE
Feature Request: include systemd --user services

### ISSUE THREAD

**Issue by two-dogs** [oguzhaninan/Stacer#98]
I tested the app on opensuse Tumbleweed and Mint 18.2 KDE, as far as i could tell all options worked correctly, having option to Start/Stop/Disable/Mask for system and user service would be great.
Just thought you should know, i dont know of another systemd-service gui out there besides yours and KDE's, Kudos, really nice app.

**Comment by oguzhaninan** [comment]
Hi,
In the new version there will be service active/inactive and enable/disable options. 
Thanks for your advice and your feedback.
